import { randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import type { RoleCode } from "./permissions.js";
import { permissionsForRole, roleExists } from "../repositories/rbac.repository.js";
import { createSessionToken } from "./token.js";
import { query } from "../db/pool.js";
import * as loginSecurity from "../repositories/login-security.repository.js";

export type AuthUserRecord={id:number;username:string;email:string;firstName:string;lastName:string;department:string;role:RoleCode;status:"ACTIVE"|"PASSIVE";passwordSalt:string;passwordHash:string};
const publicUser=async(u:AuthUserRecord)=>({id:u.id,username:u.username,email:u.email,firstName:u.firstName,lastName:u.lastName,department:u.department,role:u.role,status:u.status,permissions:await permissionsForRole(u.role)});
const verifyPassword=(password:string,saltHex:string,hashHex:string)=>{const actual=scryptSync(password,Buffer.from(saltHex,"hex"),64),expected=Buffer.from(hashHex,"hex");return actual.length===expected.length&&timingSafeEqual(actual,expected)};
const hashPassword=(password:string)=>{const salt=randomBytes(16);return{passwordSalt:salt.toString("hex"),passwordHash:scryptSync(password,salt,64).toString("hex")}};
export async function loginUser(identifier:string,password:string){if(await loginSecurity.isLocked(identifier))return null;const r=await query<AuthUserRecord>(`SELECT id,username,email,"firstName","lastName",department,role,status,"passwordSalt","passwordHash" FROM "user" WHERE lower(username)=lower($1) OR lower(email)=lower($1) LIMIT 1`,[identifier.trim()]);const u=r.rows[0];if(!u||u.status!=="ACTIVE"||!verifyPassword(password,u.passwordSalt,u.passwordHash)){await loginSecurity.failed(identifier);return null}await loginSecurity.succeeded(identifier);return{token:createSessionToken(u.id,u.role),user:await publicUser(u)}}
export async function findPublicUserById(id:number){const r=await query<AuthUserRecord>(`SELECT id,username,email,"firstName","lastName",department,role,status,"passwordSalt","passwordHash" FROM "user" WHERE id=$1 AND status='ACTIVE'`,[id]);return r.rows[0]?await publicUser(r.rows[0]):null}
export async function listPublicUsers(){const r=await query<AuthUserRecord>(`SELECT id,username,email,"firstName","lastName",department,role,status,"passwordSalt","passwordHash" FROM "user" ORDER BY id`);return Promise.all(r.rows.map(publicUser))}
export async function createUser(x:any){if(!await roleExists(x.role))throw new Error("Geçersiz rol.");if(typeof x.password!=="string"||x.password.length<8)throw new Error("Şifre en az 8 karakter olmalıdır.");const h=hashPassword(x.password);const r=await query<AuthUserRecord>(`INSERT INTO "user"(username,email,"firstName","lastName",department,role,status,"passwordSalt","passwordHash") VALUES($1,$2,$3,$4,$5,$6,'ACTIVE',$7,$8) RETURNING id,username,email,"firstName","lastName",department,role,status,"passwordSalt","passwordHash"`,[x.username.trim(),x.email.trim(),x.firstName.trim(),x.lastName.trim(),x.department?.trim()||"",x.role,h.passwordSalt,h.passwordHash]);return await publicUser(r.rows[0])}
export async function updateUser(id:number,x:any){if(x.role&&!await roleExists(x.role))throw new Error("Geçersiz rol.");const r=await query<AuthUserRecord>(`UPDATE "user" SET username=COALESCE($2,username),email=COALESCE($3,email),"firstName"=COALESCE($4,"firstName"),"lastName"=COALESCE($5,"lastName"),department=COALESCE($6,department),role=COALESCE($7,role),status=COALESCE($8,status),"updatedAt"=now() WHERE id=$1 RETURNING id,username,email,"firstName","lastName",department,role,status,"passwordSalt","passwordHash"`,[id,x.username??null,x.email??null,x.firstName??null,x.lastName??null,x.department??null,x.role??null,x.status??null]);if(!r.rows[0])throw new Error("Kullanıcı bulunamadı.");return await publicUser(r.rows[0])}
export async function changePassword(id:number,password:string){if(password.length<8)throw new Error("Şifre en az 8 karakter olmalıdır.");const h=hashPassword(password);const r=await query(`UPDATE "user" SET "passwordSalt"=$2,"passwordHash"=$3,"updatedAt"=now() WHERE id=$1 RETURNING id`,[id,h.passwordSalt,h.passwordHash]);if(!r.rowCount)throw new Error("Kullanıcı bulunamadı.");return true}
