"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { AppShell,Badge,Panel,toneFor } from "@/components/app-shell";
import { Icon } from "@/components/icon";
import { api,type ServiceRecord } from "@/lib/api";

const statusLabel:Record<string,string>={WAITING:"Bekliyor",EXAMINING:"İnceleniyor",WAITING_PART:"Parça Bekliyor",REPAIRING:"Onarımda",TESTING:"Testte",READY:"Hazır",DELIVERED:"Teslim Edildi",CANCELLED:"İptal"};
export default function ServicePage(){const [items,setItems]=useState<ServiceRecord[]>([]);const [error,setError]=useState("");useEffect(()=>{api.services().then(setItems).catch(e=>setError(e.message))},[]);return <AppShell title="Teknik Servis" subtitle="Cihaz kabulünden teslime tüm servis sürecini PostgreSQL üzerinden takip edin." actions={<Link className="btn btn-primary" href="/service/new"><Icon name="plus" size={15}/> Servis Kaydı</Link>}><div className="module-stats"><div className="mini-stat"><span>Açık Servis</span><strong>{items.filter(x=>!["DELIVERED","CANCELLED"].includes(x.status)).length}</strong><small>aktif kayıt</small></div><div className="mini-stat"><span>Parça Bekleyen</span><strong>{items.filter(x=>x.status==="WAITING_PART").length}</strong></div><div className="mini-stat"><span>Testte</span><strong>{items.filter(x=>x.status==="TESTING").length}</strong></div><div className="mini-stat"><span>Hazır</span><strong>{items.filter(x=>x.status==="READY").length}</strong></div></div>{error?<div className="inline-error">{error}</div>:null}<Panel title="Servis Kayıtları"><div className="table-wrap"><table><thead><tr><th>Servis No</th><th>Müşteri</th><th>Cihaz</th><th>Seri No</th><th>Durum</th><th>Servis Tipi</th><th>Tutar</th><th>Öncelik</th><th>Kabul</th><th></th></tr></thead><tbody>{items.map(s=><tr key={s.id}><td><Link className="strong-link mono" href={`/service/${s.id}`}>{s.serviceNo}</Link></td><td>{s.customerName}</td><td>{s.deviceName}</td><td className="mono">{s.serialNumber||"—"}</td><td><Badge tone={toneFor(statusLabel[s.status]??s.status)}>{statusLabel[s.status]??s.status}</Badge></td><td><Badge tone={s.serviceType==="WARRANTY"?"success":s.serviceType==="GOODWILL"?"primary":"warning"}>{s.serviceType==="WARRANTY"?"Garanti":s.serviceType==="GOODWILL"?"İyi Niyet":"Ücretli"}</Badge></td><td>{new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(Number(s.grandTotal??0))}</td><td>{s.priority}</td><td>{new Date(s.receivedAt).toLocaleDateString("tr-TR")}</td><td><Link className="row-link" href={`/service/${s.id}`}><Icon name="arrow" size={15}/></Link></td></tr>)}</tbody></table></div></Panel></AppShell>}
