"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";import {useRouter} from "next/navigation";import Link from "next/link";import {AppShell,Panel,PrimaryButton} from "@/components/app-shell";import {api,type Customer,type Product} from "@/lib/api";
type Line={productId:string;description:string;quantity:number;unitPrice:number;vatRate:number};
export default function NewQuote(){const r=useRouter();const[customers,setCustomers]=useState<Customer[]>([]);const[products,setProducts]=useState<Product[]>([]);const[lines,setLines]=useState<Line[]>([{productId:"",description:"",quantity:1,unitPrice:0,vatRate:20}]);const[error,setError]=useState("");const[saving,setSaving]=useState(false);useEffect(()=>{Promise.all([api.customers(),api.products()]).then(([c,p])=>{setCustomers(c);setProducts(p)}).catch(e=>setError(e.message))},[]);const totals=useMemo(()=>lines.reduce((a,l)=>{const net=l.quantity*l.unitPrice;return{sub:a.sub+net,vat:a.vat+net*l.vatRate/100}},{sub:0,vat:0}),[lines]);function changeProduct(i:number,id:string){const p=products.find(x=>String(x.id)===id);setLines(v=>v.map((l,n)=>n===i?{...l,productId:id,description:p?.name??l.description,unitPrice:Number(p?.salePrice??l.unitPrice),vatRate:Number(p?.vatRate??l.vatRate)}:l))}async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);try{const q=await api.createQuote({customerId:Number(f.get("customerId")),validUntil:f.get("validUntil")||null,notes:f.get("notes")||null,items:lines.map(l=>({...l,productId:l.productId?Number(l.productId):null}))});r.push(`/sales/${q.id}`)}catch(e){setError(e instanceof Error?e.message:"Teklif oluşturulamadı.")}finally{setSaving(false)}}return <AppShell title="Yeni Teklif" subtitle="Müşteriyi ve ürünleri seçerek teklif oluşturun."><form onSubmit={submit}>{error?<div className="inline-error">{error}</div>:null}<Panel title="Teklif Bilgileri"><div className="erp-form"><div className="form-grid"><label className="span-2"><span>Müşteri *</span><select name="customerId" required defaultValue=""><option value="" disabled>Müşteri seçin</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.code}</option>)}</select></label><label><span>Geçerlilik</span><input name="validUntil" type="date"/></label><label className="span-3"><span>Not</span><textarea name="notes" rows={2}/></label></div></div></Panel><Panel title="Teklif Kalemleri" action={<button type="button" className="btn btn-secondary" onClick={()=>setLines(v=>[...v,{productId:"",description:"",quantity:1,unitPrice:0,vatRate:20}])}>+ Kalem Ekle</button>}><div className="quote-lines">{lines.map((l,i)=><div className="quote-line" key={i}><select value={l.productId} onChange={e=>changeProduct(i,e.target.value)}><option value="">Ürün seçin</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select><input placeholder="Açıklama" value={l.description} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/><input
  type="number"
  min="1"
  step="1"
  value={l.quantity}
  onChange={e =>
    setLines(v =>
      v.map((x,n) =>
        n===i
          ? {...x, quantity: Math.max(1, Math.floor(Number(e.target.value)))}
          : x
      )
    )
  }
/><input type="number" step="0.01" value={l.unitPrice} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,unitPrice:Number(e.target.value)}:x))}/><input type="number" value={l.vatRate} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,vatRate:Number(e.target.value)}:x))}/><button type="button" className="line-remove" onClick={()=>setLines(v=>v.length>1?v.filter((_,n)=>n!==i):v)}>×</button></div>)}</div><div className="quote-total"><span>Ara Toplam <strong>{totals.sub.toLocaleString("tr-TR",{style:"currency",currency:"TRY"})}</strong></span><span>KDV <strong>{totals.vat.toLocaleString("tr-TR",{style:"currency",currency:"TRY"})}</strong></span><span>Genel Toplam <strong>{(totals.sub+totals.vat).toLocaleString("tr-TR",{style:"currency",currency:"TRY"})}</strong></span></div></Panel><div className="form-actions"><Link className="btn btn-secondary" href="/sales">İptal</Link><PrimaryButton>{saving?"Kaydediliyor…":"Teklifi Oluştur"}</PrimaryButton></div></form></AppShell>}
