"use client";
import {useAuth} from "@/lib/auth";
import Link from "next/link";import {useEffect,useState} from "react";import {AppShell,Badge,Panel} from "@/components/app-shell";import {api,type Product,type PurchaseOrder,type PurchaseRequest,type Supplier,type SupplierQuote} from "@/lib/api";
const money=(v:string)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(Number(v||0));
const status=(x:string)=>({DRAFT:"Taslak",SUBMITTED:"Onay Bekliyor",APPROVED:"Onaylandı",ORDERED:"Siparişe Döndü",OPEN:"Açık",PARTIAL:"Kısmi Kabul",RECEIVED:"Tamamlandı",CANCELLED:"İptal"}[x]||x);
export default function Purchasing(){const{user,loading}=useAuth();const[suppliers,setSuppliers]=useState<Supplier[]>([]);const[requests,setRequests]=useState<PurchaseRequest[]>([]);const[orders,setOrders]=useState<PurchaseOrder[]>([]);const[quotes,setQuotes]=useState<SupplierQuote[]>([]);const[critical,setCritical]=useState<Product[]>([]);const[error,setError]=useState("");useEffect(()=>{if(loading||!user)return;setError("");Promise.all([api.suppliers(),api.purchaseRequests(),api.purchaseOrders(),api.supplierQuotes(),api.criticalStock()]).then(([s,r,o,q,c])=>{setSuppliers(s);setRequests(r);setOrders(o);setQuotes(q);setCritical(c);setError("")}).catch(e=>setError(e.message))},[loading,user]);return <AppShell title="Satın Alma" subtitle="Tedarikçi, satın alma talebi, sipariş ve mal kabul operasyonları" actions={<div className="status-actions"><Link className="btn btn-secondary" href="/suppliers/new">+ Tedarikçi</Link><Link className="btn btn-secondary" href="/purchasing/requests/new">+ Talep</Link><Link className="btn btn-secondary" href="/purchasing/quotes/new">+ Tedarikçi Teklifi</Link><Link className="btn btn-primary" href="/purchasing/new">+ Satın Alma Siparişi</Link></div>}>{error?<div className="inline-error">{error}</div>:null}<div className="stat-grid"><div className="stat-card"><span>Kritik Stok</span><strong>{critical.length}</strong><small>satın alma adayı</small></div><div className="stat-card"><span>Açık Talep</span><strong>{requests.filter(x=>!['ORDERED','CANCELLED'].includes(x.status)).length}</strong></div><div className="stat-card"><span>Açık Sipariş</span><strong>{orders.filter(x=>!['RECEIVED','CANCELLED'].includes(x.status)).length}</strong></div><div className="stat-card"><span>Tedarikçi</span><strong>{suppliers.length}</strong></div></div>
<Panel title="Kritik Stok"><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Ürün</th><th>Stok</th><th>Kritik Seviye</th><th>Takip</th></tr></thead><tbody>{critical.length?critical.map(p=><tr key={p.id}><td className="mono">{p.sku}</td><td>{p.name}</td><td><strong>{p.isSerialized?p.deviceStock:Number(p.stockQuantity)}</strong></td><td>{p.criticalStock}</td><td><Badge tone="danger">Satın Alma Gerekli</Badge></td></tr>):<tr><td colSpan={5}>Kritik stok bulunmuyor.</td></tr>}</tbody></table></div></Panel>
<Panel title="Satın Alma Talepleri"><div className="table-wrap"><table><thead><tr><th>Talep No</th><th>Başlık</th><th>Öncelik</th><th>İsteyen</th><th>Kalem</th><th>Durum</th></tr></thead><tbody>{requests.map(x=><tr key={x.id}><td className="mono">{x.requestNo}</td><td>{x.title}</td><td><Badge tone={x.priority==='URGENT'?'danger':x.priority==='HIGH'?'warning':'neutral'}>{x.priority}</Badge></td><td>{x.requestedByName||"—"}</td><td>{x.itemCount}</td><td><Badge tone={x.status==='APPROVED'||x.status==='ORDERED'?'success':x.status==='CANCELLED'?'danger':'warning'}>{status(x.status)}</Badge></td></tr>)}</tbody></table></div></Panel>

<Panel title="Tedarikçi Teklifleri"><div className="table-wrap"><table><thead><tr><th>Teklif No</th><th>Tedarikçi</th><th>Talep</th><th>Toplam</th><th>Geçerlilik</th><th>Durum</th><th></th></tr></thead><tbody>{quotes.length?quotes.map(x=><tr key={x.id}><td className="mono">{x.quoteNo}</td><td>{x.supplierName}</td><td>{x.requestNo||"—"}</td><td>{money(x.grandTotal)}</td><td>{x.validUntil?new Date(x.validUntil).toLocaleDateString('tr-TR'):"—"}</td><td><Badge tone={x.status==='SELECTED'?'success':x.status==='REJECTED'?'danger':'warning'}>{x.status}</Badge></td><td>{x.status==='RECEIVED'?<button className="btn btn-secondary" onClick={async()=>{const o=await api.convertSupplierQuoteToOrder(String(x.id));location.href=`/purchasing/orders/${o.id}`}}>Siparişe Dönüştür</button>:null}</td></tr>):<tr><td colSpan={7}>Tedarikçi teklifi bulunmuyor.</td></tr>}</tbody></table></div></Panel>
<Panel title="Satın Alma Siparişleri"><div className="table-wrap"><table><thead><tr><th>Sipariş No</th><th>Tedarikçi</th><th>Toplam</th><th>Beklenen</th><th>Kalem</th><th>Durum</th></tr></thead><tbody>{orders.map(x=><tr key={x.id}><td><Link href={`/purchasing/orders/${x.id}`}><strong>{x.orderNo}</strong></Link></td><td>{x.supplierName}</td><td>{money(x.grandTotal)}</td><td>{x.expectedAt?new Date(x.expectedAt).toLocaleDateString('tr-TR'):"—"}</td><td>{x.itemCount??0}</td><td><Badge tone={x.status==='RECEIVED'?'success':x.status==='PARTIAL'?'warning':x.status==='CANCELLED'?'danger':'primary'}>{status(x.status)}</Badge></td></tr>)}</tbody></table></div></Panel></AppShell>}
