import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, resolve, sep } from "node:path";
import * as repo from "../repositories/document.repository.js";

const root=()=>resolve(process.env.DOCUMENT_STORAGE_PATH||resolve(process.cwd(),"storage","documents"));
const safe=(name:string)=>basename(name).replace(/[^a-zA-Z0-9._\-() ]/g,"_").slice(0,180)||"document.bin";
const allowedExtensions=new Set((process.env.DOCUMENT_ALLOWED_EXTENSIONS||"pdf,png,jpg,jpeg,webp,doc,docx,xls,xlsx,csv,txt,zip").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean));
const blockedMimes=new Set(["text/html","image/svg+xml","application/x-msdownload","application/x-sh","text/javascript","application/javascript"]);
function validateUpload(fileName:string,mimeType?:string){const ext=fileName.includes(".")?fileName.split(".").pop()!.toLowerCase():"";if(!allowedExtensions.has(ext))throw new Error("Bu dosya uzantısına izin verilmiyor.");const m=(mimeType||"").toLowerCase().split(";")[0].trim();if(blockedMimes.has(m))throw new Error("Bu dosya türüne güvenlik nedeniyle izin verilmiyor.");}
const insideRoot=(full:string)=>full===root()||full.startsWith(root()+sep);
export const categories=repo.categories;export const listDocuments=repo.list;export const getDocument=repo.byId;export const canAccessDocument=repo.canAccess;export const createDocument=repo.create;export const addDocumentLink=repo.addLink;export const removeDocumentLink=repo.removeLink;export const setDocumentStatus=repo.setStatus;export const saveDocumentAccess=repo.saveAccess;export const getDocumentSummary=repo.summary;
export async function uploadVersion(documentId:number,fileName:string,mimeType:string|undefined,body:Buffer,changeNote:string|undefined,userId?:number){const d=await repo.byId(documentId);if(!d)throw new Error('Doküman bulunamadı.');const max=Number(process.env.DOCUMENT_MAX_FILE_SIZE_MB||25)*1024*1024;if(!body.length)throw new Error('Dosya boş.');if(body.length>max)throw new Error(`Dosya boyutu ${process.env.DOCUMENT_MAX_FILE_SIZE_MB||25} MB sınırını aşıyor.`);const clean=safe(fileName);validateUpload(clean,mimeType);const versionNo=await repo.nextVersion(documentId);const storageKey=`${documentId}/v${versionNo}-${Date.now()}-${clean}`;const full=resolve(root(),storageKey);if(!insideRoot(full))throw new Error('Geçersiz dosya yolu.');await mkdir(resolve(root(),String(documentId)),{recursive:true});await writeFile(full,body,{flag:'wx'});return repo.addVersion({documentId,versionNo,fileName:clean,storageKey,mimeType,fileSize:body.length,sha256:createHash('sha256').update(body).digest('hex'),changeNote},userId)}
export async function downloadVersion(versionId:number,userId?:number,role?:string){const v=await repo.versionById(versionId);if(!v)throw new Error('Dosya sürümü bulunamadı.');if(!(await repo.canAccess(v.documentId,userId,role,false)))throw new Error('Bu dokümana erişim yetkiniz bulunmuyor.');const full=resolve(root(),v.storageKey);if(!insideRoot(full))throw new Error('Geçersiz dosya yolu.');const data=await readFile(full);await repo.audit(v.documentId,'DOWNLOAD',userId,{versionId},versionId);return {version:v,data}}
