import { query } from "../db/pool.js";
import type { Permission } from "../auth/permissions.js";

export type GlobalSearchResult = { type:string; id:number; title:string; subtitle:string; meta?:string|null; href:string };
const has=(permissions:Permission[], p:string)=>permissions.includes(p as Permission);

export async function globalSearch(term:string, permissions:Permission[], limit=30, userId?:number, role?:string):Promise<GlobalSearchResult[]> {
  const q=term.trim(); if(q.length<2) return [];
  const like=`%${q}%`; const chunks:Promise<GlobalSearchResult[]>[]=[];
  const run=(sql:string, values:unknown[]=[])=>query<GlobalSearchResult>(sql,values).then(r=>r.rows);
  if(has(permissions,"customer.view")) chunks.push(run(`SELECT 'CUSTOMER' type,id,name title,concat_ws(' · ',code,phone,"taxNumber",city) subtitle,NULL::text meta,'/customers/'||id href FROM customer WHERE name ILIKE $1 OR code ILIKE $1 OR coalesce(phone,'') ILIKE $1 OR coalesce(email,'') ILIKE $1 OR coalesce("taxNumber",'') ILIKE $1 ORDER BY name LIMIT 8`,[like]));
  if(has(permissions,"stock.view")) chunks.push(run(`SELECT 'PRODUCT' type,id,name title,concat_ws(' · ',sku,brand,category) subtitle,NULL::text meta,'/stock' href FROM product WHERE name ILIKE $1 OR sku ILIKE $1 OR coalesce(brand,'') ILIKE $1 LIMIT 6`,[like]),run(`SELECT 'DEVICE' type,d.id,d."serialNumber" title,concat_ws(' · ',p.name,p.sku,c.name) subtitle,d.status meta,'/maintenance/devices/'||d.id href FROM "inventoryDevice" d JOIN product p ON p.id=d."productId" LEFT JOIN customer c ON c.id=d."customerId" WHERE d."serialNumber" ILIKE $1 OR p.name ILIKE $1 LIMIT 8`,[like]));
  if(has(permissions,"sales.view")) chunks.push(run(`SELECT 'QUOTE' type,q.id,q."quoteNo" title,c.name subtitle,q.status meta,'/sales/'||q.id href FROM quote q JOIN customer c ON c.id=q."customerId" WHERE q."quoteNo" ILIKE $1 OR c.name ILIKE $1 LIMIT 6`,[like]),run(`SELECT 'ORDER' type,o.id,o."orderNo" title,c.name subtitle,o.status meta,'/orders/'||o.id href FROM "salesOrder" o JOIN customer c ON c.id=o."customerId" WHERE o."orderNo" ILIKE $1 OR c.name ILIKE $1 LIMIT 6`,[like]));
  if(has(permissions,"service.view")) chunks.push(run(`SELECT 'SERVICE' type,s.id,s."serviceNo" title,concat_ws(' · ',c.name,s."deviceName",s."serialNumber") subtitle,s.status meta,'/service/'||s.id href FROM "serviceRecord" s JOIN customer c ON c.id=s."customerId" WHERE s."serviceNo" ILIKE $1 OR c.name ILIKE $1 OR coalesce(s."serialNumber",'') ILIKE $1 OR s."deviceName" ILIKE $1 OR s.problem ILIKE $1 LIMIT 8`,[like]));
  if(has(permissions,"support.view")) chunks.push(run(`SELECT 'TICKET' type,t.id,t."ticketNo" title,concat_ws(' · ',c.name,t.subject) subtitle,t.status meta,'/support/'||t.id href FROM "supportTicket" t JOIN customer c ON c.id=t."customerId" WHERE t."ticketNo" ILIKE $1 OR t.subject ILIKE $1 OR t.description ILIKE $1 OR c.name ILIKE $1 LIMIT 8`,[like]));
  if(has(permissions,"cors.view")) chunks.push(run(`SELECT 'CORS' type,s.id,s."subscriptionNo" title,concat_ws(' · ',c.name,s.username) subtitle,s.status meta,'/cors/subscriptions/'||s.id href FROM "corsSubscription" s JOIN customer c ON c.id=s."customerId" WHERE s."subscriptionNo" ILIKE $1 OR s.username ILIKE $1 OR c.name ILIKE $1 LIMIT 8`,[like]));
  if(has(permissions,"project.view")) chunks.push(run(`SELECT 'PROJECT' type,p.id,p.code title,concat_ws(' · ',p.name,c.name,p.city) subtitle,p.status meta,'/projects/'||p.id href FROM project p LEFT JOIN customer c ON c.id=p."customerId" WHERE p.code ILIKE $1 OR p.name ILIKE $1 OR coalesce(c.name,'') ILIKE $1 OR coalesce(p.city,'') ILIKE $1 LIMIT 8`,[like]));
  if(has(permissions,"document.view")) chunks.push(run(`SELECT 'DOCUMENT' type,d.id,d."documentNo" title,concat_ws(' · ',d.title,dc.name) subtitle,d.status meta,'/documents/'||d.id href FROM document d LEFT JOIN "documentCategory" dc ON dc.id=d."categoryId" WHERE (d."documentNo" ILIKE $1 OR d.title ILIKE $1 OR coalesce(d.description,'') ILIKE $1) AND (d."accessLevel"<>'RESTRICTED' OR $2='ADMIN' OR d."ownerUserId"=$3 OR d."createdBy"=$3 OR EXISTS(SELECT 1 FROM "documentAccessRule" ar WHERE ar."documentId"=d.id AND ar."canView"=TRUE AND (ar."userId"=$3 OR ar."roleCode"=$2))) LIMIT 8`,[like,role??'',userId??0]));
  const groups=await Promise.all(chunks); return groups.flat().slice(0,Math.min(Math.max(limit,1),50));
}
