import * as repo from "../repositories/invoice.repository.js";

const base="https://api.parasut.com/v4";
function config(){return {companyId:process.env.PARASUT_COMPANY_ID||"",clientId:process.env.PARASUT_CLIENT_ID||"",clientSecret:process.env.PARASUT_CLIENT_SECRET||"",refreshToken:process.env.PARASUT_REFRESH_TOKEN||""}}
export function status(){const c=config();return {provider:"PARASUT",configured:Boolean(c.companyId&&c.clientId&&c.clientSecret&&c.refreshToken),companyId:c.companyId||null,mode:"API_V4",baseUrl:base,defaultAccountId:process.env.PARASUT_DEFAULT_ACCOUNT_ID||null}}
async function token(){const c=config();if(!status().configured)throw new Error("Paraşüt API bağlantısı yapılandırılmamış. PARASUT_COMPANY_ID, PARASUT_CLIENT_ID, PARASUT_CLIENT_SECRET ve PARASUT_REFRESH_TOKEN gerekli.");const r=await fetch("https://api.parasut.com/oauth/token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({grant_type:"refresh_token",client_id:c.clientId,client_secret:c.clientSecret,refresh_token:c.refreshToken})});if(!r.ok)throw new Error(`Paraşüt OAuth başarısız (${r.status}).`);return (await r.json() as any).access_token as string}
async function request(path:string,init:RequestInit={}){const t=await token();const r=await fetch(`${base}/${config().companyId}${path}`,{...init,headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json","Accept":"application/json",...(init.headers||{})}});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(`Paraşüt API ${r.status}: ${JSON.stringify(body)?.slice(0,500)}`);return body}

async function ensureContact(invoice:any){const kind=invoice.direction==='SALE'?'CUSTOMER':'SUPPLIER';const localId=invoice.direction==='SALE'?invoice.customerId:invoice.supplierId;const entityType=kind==='CUSTOMER'?'customer':'supplier';const existing=await repo.getLink(entityType,localId);if(existing)return existing.externalId;const name=invoice.direction==='SALE'?invoice.customerName:invoice.supplierName;const tax=invoice.direction==='SALE'?invoice.customerTaxNumber:invoice.supplierTaxNumber;const email=invoice.direction==='SALE'?invoice.customerEmail:invoice.supplierEmail;const city=invoice.direction==='SALE'?invoice.customerCity:invoice.supplierCity;const address=invoice.direction==='SALE'?invoice.customerAddress:invoice.supplierAddress;const taxOffice=invoice.direction==='SALE'?invoice.customerTaxOffice:invoice.supplierTaxOffice;if(tax){const found=await request(`/contacts?filter[tax_number]=${encodeURIComponent(tax)}`);if(found?.data?.[0]){await repo.saveLink(entityType,localId,String(found.data[0].id));return String(found.data[0].id)}}const created=await request(`/contacts`,{method:'POST',body:JSON.stringify({data:{type:'contacts',attributes:{name,email:email||null,tax_number:tax||null,tax_office:taxOffice||null,city:city||null,address:address||null,account_type:kind==='CUSTOMER'?'customer':'supplier'}}})});await repo.saveLink(entityType,localId,String(created.data.id));return String(created.data.id)}

async function ensureProduct(item:any){if(!item.productId)return null;const existing=await repo.getLink('product',item.productId);if(existing)return existing.externalId;const found=await request(`/products?filter[code]=${encodeURIComponent(item.sku||'')}`);if(found?.data?.[0]){await repo.saveLink('product',item.productId,String(found.data[0].id),item.sku);return String(found.data[0].id)}const created=await request(`/products`,{method:'POST',body:JSON.stringify({data:{type:'products',attributes:{name:item.productName||item.description,code:item.sku||undefined,vat_rate:Number(item.vatRate||20),unit:item.unit||'Adet'}}})});await repo.saveLink('product',item.productId,String(created.data.id),item.sku);return String(created.data.id)}

function virtualDef(sourceType:string){if(sourceType==='SERVICE')return {id:1,code:'ESKA-SERVIS',name:'Teknik Servis Hizmeti'};if(sourceType==='CORS_RENEWAL')return {id:3,code:'ESKA-CORS-YENILEME',name:'CORS Abonelik Yenileme'};return {id:2,code:'ESKA-CORS',name:'CORS Abonelik Hizmeti'}}
async function ensureVirtualProduct(sourceType:string,vat:number){const v=virtualDef(sourceType);const existing=await repo.getLink('virtual_product',v.id);if(existing)return existing.externalId;const found=await request(`/products?filter[code]=${encodeURIComponent(v.code)}`);if(found?.data?.[0]){await repo.saveLink('virtual_product',v.id,String(found.data[0].id),v.code);return String(found.data[0].id)}const created=await request('/products',{method:'POST',body:JSON.stringify({data:{type:'products',attributes:{name:v.name,code:v.code,vat_rate:vat,unit:'Adet'}}})});await repo.saveLink('virtual_product',v.id,String(created.data.id),v.code);return String(created.data.id)}

export async function pushInvoice(id:number){const invoice=await repo.getInvoice(id);if(!invoice)throw new Error("Fatura bulunamadı.");try{const contactId=await ensureContact(invoice);const details=[];for(const item of invoice.items){const productId=await ensureProduct(item)||await ensureVirtualProduct(invoice.sourceType,Number(item.vatRate||20));details.push({type:invoice.direction==='SALE'?'sales_invoice_details':'purchase_bill_details',attributes:{quantity:Number(item.quantity),unit_price:Number(item.unitPrice),vat_rate:Number(item.vatRate)},relationships:{product:{data:{type:'products',id:String(productId)}}}})}const sale=invoice.direction==='SALE';const type=sale?'sales_invoices':'purchase_bills';const path=sale?'/sales_invoices':'/purchase_bills#detailed';const relationships:any={details:{data:details}};relationships[sale?'contact':'supplier']={data:{type:'contacts',id:String(contactId)}};const body={data:{type,attributes:{issue_date:String(invoice.issueDate).slice(0,10),due_date:invoice.dueDate?String(invoice.dueDate).slice(0,10):null,description:invoice.notes||invoice.invoiceNo,item_type:sale?'invoice':'purchase_bill',currency:invoice.currency==='TRY'?'TRL':invoice.currency},relationships}};const result=await request(path,{method:'POST',body:JSON.stringify(body)});const ext=String(result.data.id);await repo.saveLink(sale?'sales_invoice':'purchase_bill',id,ext,result.data?.attributes?.invoice_no);await repo.markSync(id,{status:'SYNCED',externalId:ext,externalNo:result.data?.attributes?.invoice_no||null});await repo.logSync('PUSH_INVOICE','commercialInvoice',id,'SUCCESS','Fatura Paraşüt\'e aktarıldı.',ext);return {invoice:await repo.getInvoice(id),external:result.data}}catch(e){const m=e instanceof Error?e.message:String(e);await repo.markSync(id,{status:'ERROR',error:m});await repo.logSync('PUSH_INVOICE','commercialInvoice',id,'ERROR',m);throw e}}

export async function testConnection(){const me=await request('/me');await repo.logSync('TEST_CONNECTION',null,null,'SUCCESS','Paraşüt bağlantısı doğrulandı.');return {ok:true,user:me?.data||me}}

export async function pushFinanceTransaction(id:number){const existing=await repo.getLink('financeTransaction',id);if(existing)return {alreadySynced:true,externalId:existing.externalId};const t=await repo.getFinanceTransactionForParasut(id);if(!t)throw new Error("Tahsilat/ödeme için bağlı finans belgesi bulunamadı.");if(!t.invoiceExternalId||t.invoiceStatus!=='SYNCED')throw new Error("Önce ilgili satış/alış faturası Paraşüt’e aktarılmalıdır.");const mapping=await repo.getAccountMapping(Number(t.accountId));const accountId=mapping?.externalAccountId||process.env.PARASUT_DEFAULT_ACCOUNT_ID;if(!accountId)throw new Error("Bu ESKA kasa/banka hesabı için Paraşüt hesap eşlemesi bulunmuyor.");try{const path=t.direction==='SALE'?`/sales_invoices/${t.invoiceExternalId}/payments`:`/purchase_bills/${t.invoiceExternalId}/payments`;const result=await request(path,{method:'POST',body:JSON.stringify({data:{type:'payments',attributes:{description:t.description||t.transactionNo,account_id:Number(accountId),date:String(t.transactionDate).slice(0,10),amount:Number(t.amount),exchange_rate:1}}})});const ext=String(result.data.id);await repo.saveLink('financeTransaction',id,ext);await repo.logSync('PUSH_PAYMENT','financeTransaction',id,'SUCCESS','Tahsilat/ödeme Paraşüt’e aktarıldı.',ext);return result.data}catch(e){const m=e instanceof Error?e.message:String(e);await repo.logSync('PUSH_PAYMENT','financeTransaction',id,'ERROR',m);throw e}}

export async function enqueueInvoice(id:number,userId?:number){const inv=await repo.getInvoice(id);if(!inv)throw new Error('Fatura bulunamadı.');return repo.enqueueSyncJob('PUSH_INVOICE','commercialInvoice',id,userId)}
export async function enqueueFinanceTransaction(id:number,userId?:number){return repo.enqueueSyncJob('PUSH_PAYMENT','financeTransaction',id,userId)}
export async function processQueue(limit=10){const jobs=await repo.claimSyncJobs(limit);const results=[] as any[];for(const job of jobs){try{let result:any;if(job.action==='PUSH_INVOICE')result=await pushInvoice(job.localId);else if(job.action==='PUSH_PAYMENT')result=await pushFinanceTransaction(job.localId);else throw new Error(`Desteklenmeyen Paraşüt işi: ${job.action}`);const externalId=String(result?.external?.id||result?.externalId||result?.id||'')||null;await repo.finishSyncJob(Number(job.id),externalId);results.push({id:job.id,status:'SUCCESS'})}catch(e){const message=e instanceof Error?e.message:String(e);const failed=await repo.failSyncJob(Number(job.id),message);results.push({id:job.id,status:failed.status,error:message})}}return {processed:results.length,results,summary:await repo.syncQueueSummary()}}
export const queue=repo.syncJobs;export const retryJob=repo.retrySyncJob;export const queueSummary=repo.syncQueueSummary;
