"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {AppShell,Badge,Panel} from "@/components/app-shell";import {api,type VatReportRow,type EDocumentReadiness} from "@/lib/api";
const money=(v:string|number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(Number(v||0));
const source=(v:string)=>({SALES_ORDER:"Satış Siparişi",PURCHASE_ORDER:"Satın Alma",SERVICE:"Teknik Servis",CORS_SUBSCRIPTION:"CORS Aboneliği",CORS_RENEWAL:"CORS Yenileme"}[v]||v);
export default function FinanceReports(){const[vat,setVat]=useState<VatReportRow[]>([]);const[docs,setDocs]=useState<EDocumentReadiness[]>([]);const[from,setFrom]=useState("");const[to,setTo]=useState("");const[error,setError]=useState("");async function load(){try{const[v,d]=await Promise.all([api.financeVatReport(from||undefined,to||undefined),api.eDocumentReadiness()]);setVat(v);setDocs(d)}catch(e){setError(e instanceof Error?e.message:"Raporlar yüklenemedi.")}}useEffect(()=>{void load()},[]);const sale=vat.find(x=>x.direction==='SALE'),purchase=vat.find(x=>x.direction==='PURCHASE');
return <AppShell title="Finans Raporları" subtitle="KDV özeti, e-belge hazırlık kontrolü ve muhasebe aktarım kalitesi" actions={<><Link className="btn btn-secondary" href="/finance">Finansa Dön</Link><Link className="btn btn-secondary" href="/finance/parasut">Paraşüt</Link></>}>
{error?<div className="inline-error">{error}</div>:null}<div className="stat-grid"><div className="stat-card"><span>Satış KDV</span><strong>{money(sale?.vatTotal||0)}</strong><small>{sale?.count||0} belge</small></div><div className="stat-card"><span>Alış KDV</span><strong>{money(purchase?.vatTotal||0)}</strong><small>{purchase?.count||0} belge</small></div><div className="stat-card"><span>Net KDV Pozisyonu</span><strong>{money(Number(sale?.vatTotal||0)-Number(purchase?.vatTotal||0))}</strong><small>Satış KDV − Alış KDV</small></div><div className="stat-card"><span>e-Belge Hazır</span><strong>{docs.filter(x=>x.ready).length}/{docs.length}</strong><small>Temel cari bilgileri tam</small></div></div>
<Panel title="KDV Dönem Filtresi"><div className="form-grid"><label><span>Başlangıç</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span>Bitiş</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="form-actions"><button className="btn btn-primary" onClick={load}>Raporu Güncelle</button></div></Panel>
<Panel title="KDV Özeti"><div className="table-wrap"><table><thead><tr><th>Tür</th><th>Belge</th><th>Matrah</th><th>KDV</th><th>Genel Toplam</th></tr></thead><tbody>{vat.map(x=><tr key={x.direction}><td><strong>{x.direction==='SALE'?'Satış':'Alış'}</strong></td><td>{x.count}</td><td>{money(x.subtotal)}</td><td>{money(x.vatTotal)}</td><td><strong>{money(x.grandTotal)}</strong></td></tr>)}</tbody></table></div></Panel>
<Panel title="e-Fatura / e-Arşiv Hazırlık Kontrolü"><div className="table-wrap"><table><thead><tr><th>Belge</th><th>Cari</th><th>Kaynak</th><th>VKN/TCKN</th><th>Adres</th><th>Hazırlık</th><th>e-Belge</th></tr></thead><tbody>{docs.map(x=><tr key={x.id}><td className="mono">{x.invoiceNo}</td><td><strong>{x.partyName||'—'}</strong></td><td>{source(x.sourceType)}</td><td>{x.taxNumber||'Eksik'}</td><td>{x.city&&x.address?`${x.city} · ${x.address}`:'Eksik'}</td><td><Badge tone={x.ready?'success':'danger'}>{x.ready?'Hazır':'Eksik Bilgi'}</Badge></td><td>{x.eDocumentType} · {x.eDocumentStatus}</td></tr>)}</tbody></table></div></Panel>
</AppShell>}
