"use client";
import {useEffect,useState} from "react";import {AppShell} from "@/components/app-shell";import {api} from "@/lib/api";
const fmt=(x:string)=>new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"medium"}).format(new Date(x));
export default function AuditPage(){const [data,setData]=useState<any>({items:[],total:0});const [summary,setSummary]=useState<any>({today:0,week:0,users:0});const [q,setQ]=useState("");const [module,setModule]=useState("");
 const load=()=>api.auditLogs({...q&&{q},...module&&{module}}).then(setData).catch(()=>setData({items:[],total:0}));
 useEffect(()=>{load();api.auditSummary().then(setSummary).catch(()=>{})},[]);
 return <AppShell title="Sistem Hareketleri" subtitle="Kritik ERP işlemlerinin merkezi denetim kaydı">
 <div className="metric-grid"><div className="metric-card"><span>Bugün</span><strong>{summary.today}</strong><small>işlem</small></div><div className="metric-card"><span>Son 7 gün</span><strong>{summary.week}</strong><small>işlem</small></div><div className="metric-card"><span>Aktif kullanıcı</span><strong>{summary.users}</strong><small>7 günlük</small></div><div className="metric-card"><span>Filtre sonucu</span><strong>{data.total}</strong><small>kayıt</small></div></div>
 <section className="panel"><div className="panel-head"><div><h2>Audit Log</h2><p>Kullanıcı, işlem, kayıt ve istek bilgileri</p></div><div style={{display:"flex",gap:8}}><input className="input" placeholder="Kayıt, kullanıcı, ID ara" value={q} onChange={e=>setQ(e.target.value)}/><select className="input" value={module} onChange={e=>setModule(e.target.value)}><option value="">Tüm modüller</option>{["CUSTOMER","SALES","FINANCE","SERVICE","CORS","SUPPORT","PROJECT","STOCK","PURCHASE","RENTAL","MAINTENANCE","DOCUMENT"].map(x=><option key={x}>{x}</option>)}</select><button className="btn btn-primary" onClick={load}>Filtrele</button></div></div>
 <div className="table-wrap"><table><thead><tr><th>Tarih</th><th>Kullanıcı</th><th>Modül</th><th>İşlem</th><th>Kayıt</th><th>IP</th><th>Detay</th></tr></thead><tbody>{data.items.map((x:any)=><tr key={x.id}><td>{fmt(x.createdAt)}</td><td>{x.username||x.userRole||"Sistem"}</td><td><span className="status-pill">{x.module}</span></td><td>{x.action}</td><td>{x.entityLabel||x.entityId||"—"}</td><td>{x.ipAddress||"—"}</td><td><details><summary>Görüntüle</summary><pre style={{whiteSpace:"pre-wrap",maxWidth:520,fontSize:11}}>{JSON.stringify({old:x.oldValues,new:x.newValues,metadata:x.metadata,requestId:x.requestId,path:x.requestPath},null,2)}</pre></details></td></tr>)}{!data.items.length?<tr><td colSpan={7}>Audit kaydı bulunamadı.</td></tr>:null}</tbody></table></div></section>
 </AppShell>}
