"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {AppShell,Badge,Panel} from "@/components/app-shell";import {api,type CommercialInvoice,type ParasutStatus} from "@/lib/api";
const money=(v:string|number,c="TRY")=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:c}).format(Number(v||0));
const source=(v:string)=>({SALES_ORDER:"Satış Siparişi",PURCHASE_ORDER:"Satın Alma",SERVICE:"Teknik Servis",CORS_SUBSCRIPTION:"CORS Aboneliği",CORS_RENEWAL:"CORS Yenileme"}[v]||v);
export default function FinanceInvoices(){const[rows,setRows]=useState<CommercialInvoice[]>([]);const[ps,setPs]=useState<ParasutStatus|null>(null);const[busy,setBusy]=useState<number|null>(null);const[error,setError]=useState("");async function load(){try{const[r,p]=await Promise.all([api.financeInvoices(),api.parasutStatus()]);setRows(r);setPs(p)}catch(e){setError(e instanceof Error?e.message:"Faturalar yüklenemedi.")}}useEffect(()=>{void load()},[]);
async function sync(){setError("");try{await api.syncInvoiceSources();await load()}catch(e){setError(e instanceof Error?e.message:"Kaynak eşitleme başarısız.")}}
async function push(id:number){setBusy(id);setError("");try{await api.pushInvoiceToParasut(String(id));await load()}catch(e){setError(e instanceof Error?e.message:"Paraşüt aktarımı başarısız.")}finally{setBusy(null)}}
return <AppShell title="Faturalar" subtitle="Satış ve alış faturaları · Paraşüt aktarım kuyruğu" actions={<><Link className="btn btn-secondary" href="/finance/parasut">Paraşüt Bağlantısı</Link><button className="btn btn-primary" onClick={sync}>Kaynakları Eşitle</button></>}>
{error?<div className="inline-error">{error}</div>:null}<div className="stat-grid"><div className="stat-card"><span>Toplam Fatura</span><strong>{rows.length}</strong><small>Satış + alış</small></div><div className="stat-card"><span>Paraşüt Aktarılan</span><strong>{rows.filter(x=>x.status==='SYNCED').length}</strong><small>Senkron kayıt</small></div><div className="stat-card"><span>Aktarım Bekleyen</span><strong>{rows.filter(x=>x.status==='READY').length}</strong><small>Hazır kayıt</small></div><div className="stat-card"><span>Paraşüt</span><strong>{ps?.configured?'Bağlı':'Kurulum Gerekli'}</strong><small>{ps?.companyId?`Firma ${ps.companyId}`:'API bilgileri eksik'}</small></div></div>
<Panel title="Fatura Listesi"><div className="table-wrap"><table><thead><tr><th>Fatura</th><th>Tür</th><th>Kaynak</th><th>Cari</th><th>Tarih</th><th>Toplam</th><th>Durum</th><th>Paraşüt</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td className="mono">{x.invoiceNo}</td><td>{x.direction==='SALE'?'Satış':'Alış'}</td><td>{source(x.sourceType)}</td><td><strong>{x.customerName||x.supplierName||'—'}</strong></td><td>{new Date(x.issueDate).toLocaleDateString('tr-TR')}</td><td><strong>{money(x.grandTotal,x.currency)}</strong></td><td><Badge tone={x.status==='SYNCED'?'success':x.status==='ERROR'?'danger':'warning'}>{x.status==='SYNCED'?'Senkron':x.status==='ERROR'?'Hata':'Hazır'}</Badge></td><td>{x.externalNo||x.externalId||'—'}{x.syncError?<><br/><small>{x.syncError.slice(0,80)}</small></>:null}</td><td>{x.status!=='SYNCED'?<button className="btn btn-secondary" disabled={!ps?.configured||busy===x.id} onClick={()=>push(x.id)}>{busy===x.id?'Aktarılıyor…':'Paraşüt’e Aktar'}</button>:null}</td></tr>)}{!rows.length?<tr><td colSpan={9}>Henüz fatura kaydı yok.</td></tr>:null}</tbody></table></div></Panel></AppShell>}
