const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
let authToken: string | null = null;

export type ApiEnvelope<T> = { success: boolean; message?: string; data: T };
export type CurrentUser = {id:number;username:string;email:string;firstName:string;lastName:string;department:string;role:string;status:"ACTIVE"|"PASSIVE";permissions:string[]};
export type Customer = {id:number;code:string;type:"COMPANY"|"PERSON";name:string;taxOffice:string|null;taxNumber:string|null;contactName:string|null;email:string|null;phone:string|null;city:string|null;district:string|null;address:string|null;status:"ACTIVE"|"PASSIVE";notes:string|null;creditLimit:string;riskPolicy:"WARN"|"BLOCK";paymentTermDays:number;riskNotes:string|null;createdAt:string;updatedAt:string};
export type CustomerInput = Partial<Omit<Customer,"id"|"createdAt"|"updatedAt">> & { name:string };
export type ServiceOperation={id:number;serviceRecordId:number;type:string;description:string;laborMinutes:number;amount:string;performedBy:number|null;performedByName?:string|null;createdAt:string};
export type ServicePart={id:number;serviceRecordId:number;productId:number;quantity:string;unitPrice:string;lineTotal:string;productName:string;sku:string;createdAt:string};
export type ServiceStatusHistory={id:number;serviceRecordId:number;fromStatus:string|null;toStatus:string;note:string|null;changedBy:number|null;changedByName?:string|null;createdAt:string};
export type ServiceRecord = {id:number;serviceNo:string;customerId:number;customerName:string;deviceId:number|null;serialNumber:string|null;deviceName:string;productName?:string|null;problem:string;status:string;priority:string;receivedAt:string;completedAt:string|null;notes:string|null;serviceType:string;warrantyCovered:boolean;diagnosis:string|null;resolution:string|null;laborTotal:string;partsTotal:string;grandTotal:string;paymentStatus:string;operations?:ServiceOperation[];parts?:ServicePart[];statusHistory?:ServiceStatusHistory[]};
export type Product = {id:number;sku:string;name:string;brand:string|null;category:string|null;unit:string;salePrice:string|null;vatRate:string;criticalStock:number;isSerialized:boolean;stockQuantity:string;status:"ACTIVE"|"PASSIVE";deviceStock?:number};
export type InventoryDevice = {id:number;productId:number;serialNumber:string;status:string;customerId:number|null;productName:string;sku:string;customerName:string|null;salesOrderId?:number|null;orderNo?:string|null;soldAt?:string|null;deliveredAt?:string|null;warrantyStartAt?:string|null;warrantyEndAt?:string|null;warrantyMonths?:number};
export type Quote = {id:number;quoteNo:string;customerId:number;customerName:string;status:string;validUntil:string|null;currency:string;subtotal:string;vatTotal:string;grandTotal:string;notes:string|null;itemCount?:number;items?:Array<{id:number;productId:number|null;description:string;quantity:string;unitPrice:string;vatRate:string;lineTotal:string;productName?:string|null;sku?:string|null;isSerialized?:boolean}>};
export type SalesOrderItem={id:number;productId:number|null;description:string;quantity:string;unitPrice:string;vatRate:string;lineTotal:string;productName?:string|null;sku?:string|null;isSerialized?:boolean};
export type SalesOrder = {id:number;orderNo:string;quoteId:number|null;customerId:number;customerName:string;status:string;currency:string;subtotal:string;vatTotal:string;grandTotal:string;itemCount?:number;createdAt:string;updatedAt?:string;deliveredAt?:string|null;deliveryNote?:string|null;items?:SalesOrderItem[];devices?:InventoryDevice[]};
export type StockMovement={id:number;productId:number;deviceId:number|null;type:string;quantity:string;referenceType:string|null;referenceId:number|null;notes:string|null;createdAt:string;productName:string;sku:string;serialNumber:string|null;createdByUsername:string|null;createdByName:string|null};


export type CorsPackage={id:number;code:string;name:string;durationMonths:number;price:string;currency:string;maxDevices:number;description:string|null;isActive:boolean};
export type CorsRenewal={id:number;subscriptionId:number;previousEndDate:string;newEndDate:string;amount:string;paymentStatus:string;note:string|null;createdAt:string};
export type CorsSubscription={id:number;subscriptionNo:string;customerId:number;customerName:string;packageId:number;packageName:string;stationId:number|null;stationCode:string|null;username:string;status:string;paymentStatus:string;startDate:string;endDate:string;remainingDays:number;amount:string;currency:string;notes:string|null;renewals?:CorsRenewal[]};
export type CorsSubscriptionSummary={total:number;active:number;expiring30:number;unpaid:number;activeValue:string};
export type CorsStationEvent={id:number;stationId:number;stationCode:string;stationName:string;city:string|null;type:string;status:string|null;message:string|null;occurredAt:string;resolvedAt:string|null};
export type CorsMaintenance={id:number;stationId:number;stationCode:string;stationName:string;city:string|null;title:string;description:string|null;status:string;scheduledAt:string;completedAt:string|null;createdAt:string};
export type CorsUptime={id:number;code:string;name:string;city:string|null;offline_seconds:string|number;uptimePercent:string};
export type CorsRevenue={month:string;newSales:string;renewals:string;total:string};
export type AppNotification={id:number;type:string;severity:string;title:string;message:string;entityType:string|null;entityId:number|null;actionUrl:string|null;isRead:boolean;createdAt:string;readAt:string|null};
export type NotificationSummary={unread:number;critical:number};
export type GlobalSearchResult={type:string;id:number;title:string;subtitle:string;meta?:string|null;href:string};

export type SupportTicketComment={id:number;ticketId:number;type:string;visibility:string;body:string;createdBy:number|null;createdByName?:string|null;createdAt:string};
export type SupportTicket={id:number;ticketNo:string;customerId:number;customerName:string;subject:string;description:string;module:string;channel:string;priority:string;status:string;department:string|null;assignedUserId:number|null;assignedUserName:string|null;serviceRecordId:number|null;serviceNo:string|null;deviceId:number|null;serialNumber:string|null;deviceName:string|null;corsSubscriptionId:number|null;subscriptionNo:string|null;corsUsername:string|null;slaFirstResponseDueAt:string;slaResolutionDueAt:string;firstRespondedAt:string|null;resolvedAt:string|null;closedAt:string|null;resolution:string|null;createdAt:string;updatedAt:string;comments?:SupportTicketComment[]};
export type SupportSummary={open:number;highPriority:number;waitingCustomer:number;slaBreached:number;resolvedToday:number;slaSuccess:string};


export type GroupCompany={id:number;code:string;name:string;isActive:boolean};
export type ProjectTask={id:number;projectId:number;code:string;title:string;category:string;status:string;priority:string;assignedUserId:number|null;assignedPerson:string|null;plannedStartAt:string|null;dueAt:string|null;completedAt:string|null;progress:number;location:string|null;notes:string|null;createdAt:string;updatedAt:string};
export type ProjectAssignment={id:number;projectId:number;userId:number|null;employeeName:string;department:string|null;role:string;homeCompanyId:number|null;homeCompanyName:string|null;assignedCompanyId:number|null;assignedCompanyName:string|null;startDate:string|null;endDate:string|null;status:string;notes:string|null;createdAt:string};
export type ProjectMilestone={id:number;projectId:number;title:string;status:string;targetDate:string|null;completedAt:string|null;sortOrder:number;notes:string|null;createdAt:string};
export type ErpProject={id:number;code:string;customerId:number|null;customerName:string|null;ownerCompanyId:number|null;ownerCompanyName:string|null;type:string;name:string;status:string;stage:string;city:string|null;district:string|null;address:string|null;latitude:string|null;longitude:string|null;acPowerMw:string|null;dcPowerMwp:string|null;startDate:string|null;targetEndDate:string|null;completedAt:string|null;progress:number;description:string|null;taskCount:number;doneTaskCount:number;teamCount:number;createdAt:string;updatedAt:string;tasks?:ProjectTask[];assignments?:ProjectAssignment[];milestones?:ProjectMilestone[]};
export type ProjectSummary={active:number;activeGes:number;planning:number;due30:number;gesPowerMwp:string;fieldTeam:number};
export type WorkTask={id:number;taskNo:string;title:string;description:string|null;sourceType:string;sourceId:number|null;sourceLabel:string|null;status:string;priority:string;assignedUserId:number|null;assignedUserName:string|null;department:string|null;companyId:number|null;companyName:string|null;createdBy:number|null;createdByName:string|null;startAt:string|null;dueAt:string|null;completedAt:string|null;progress:number;notes:string|null;overdue?:boolean;createdAt:string;updatedAt:string};
export type WorkTaskSummary={mine:number;inProgress:number;overdue:number;due7:number;team:number};
export type TaskAssignee={id:number;name:string;department:string;role:string};
export type Supplier={id:number;code:string;name:string;taxOffice:string|null;taxNumber:string|null;contactName:string|null;email:string|null;phone:string|null;city:string|null;address:string|null;status:string;notes:string|null;createdAt:string;updatedAt:string};
export type PurchaseRequest={id:number;requestNo:string;title:string;status:string;priority:string;requestedBy:number|null;requestedByName:string|null;neededBy:string|null;notes:string|null;itemCount:number;createdAt:string;updatedAt:string};
export type PurchaseOrderItem={id:number;orderId:number;productId:number;description:string;quantity:string;receivedQuantity:string;unitPrice:string;vatRate:string;lineTotal:string;productName:string;sku:string;isSerialized:boolean};
export type SupplierQuote={id:number;quoteNo:string;supplierId:number;supplierName:string;requestId:number|null;requestNo:string|null;status:string;currency:string;validUntil:string|null;grandTotal:string;notes:string|null;itemCount:number;createdAt:string};
export type PurchaseOrder={id:number;orderNo:string;supplierId:number;supplierName:string;requestId:number|null;status:string;currency:string;subtotal:string;vatTotal:string;grandTotal:string;expectedAt:string|null;notes:string|null;itemCount?:number;createdAt:string;updatedAt:string;items?:PurchaseOrderItem[];receipts?:Array<{id:number;receiptNo:string;deliveryNoteNo:string|null;receivedAt:string;notes:string|null}>};


export class ApiError extends Error { constructor(public status:number,message:string){super(message);this.name="ApiError";} }
export function setAuthToken(token:string|null){authToken=token;}
export async function apiFetch<T>(path:string,init?:RequestInit):Promise<T>{const headers=new Headers(init?.headers);if(!(init?.body instanceof Blob)&&!(init?.body instanceof ArrayBuffer)&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");if(authToken)headers.set("Authorization",`Bearer ${authToken}`);const response=await fetch(`${API_URL}${path}`,{...init,headers,cache:"no-store"});const body=await response.json().catch(()=>null);if(!response.ok)throw new ApiError(response.status,body?.message??"Ä°ÅŸlem sÄ±rasÄ±nda bir hata oluÅŸtu.");return (body?.data??body) as T;}


export type FinanceAccount={id:number;code:string;name:string;type:"CASH"|"BANK";currency:string;openingBalance:string;balance?:string;isActive:boolean};

export type CustomerRisk={id:number;name:string;creditLimit:number;riskPolicy:"WARN"|"BLOCK";paymentTermDays:number;riskNotes:string|null;openBalance:number;overdueBalance:number;maxOverdueDays:number;proposedAmount:number;projectedExposure:number;availableLimit:number|null;utilizationPercent:number;limitExceeded:boolean;severeOverdue:boolean;canOrder:boolean;riskLevel:"GOOD"|"WARNING"|"CRITICAL"|"BLOCKED"};
export type ReceivableAging={customerId:number;code:string;name:string;creditLimit:string;riskPolicy:string;current:string;days1to30:string;days31to60:string;days61to90:string;days90plus:string;total:string};
export type FinanceDocument={id:number;documentNo:string;partyType:"CUSTOMER"|"SUPPLIER";customerId:number|null;supplierId:number|null;direction:"RECEIVABLE"|"PAYABLE";sourceType:string;sourceId:number;description:string;currency:string;amount:string;paidAmount:string;balance:string;dueDate:string|null;status:string;customerName?:string|null;supplierName?:string|null;createdAt:string};
export type FinanceTransaction={id:number;transactionNo:string;type:"RECEIPT"|"PAYMENT"|"ADJUSTMENT";accountId:number;accountName:string;partyType:string|null;customerId:number|null;supplierId:number|null;customerName?:string|null;supplierName?:string|null;currency:string;amount:string;description:string|null;transactionDate:string;createdByName:string|null;createdAt:string};
export type FinanceSummary={totalReceivable:string;totalPayable:string;overdueReceivable:string;openDocuments:number;accounts:FinanceAccount[]};
export type FinanceLedger={documents:FinanceDocument[];transactions:FinanceTransaction[]};
export type CommercialInvoice={id:number;invoiceNo:string;direction:"SALE"|"PURCHASE";customerId:number|null;supplierId:number|null;customerName?:string|null;supplierName?:string|null;sourceType:string;sourceId:number;issueDate:string;dueDate:string|null;currency:string;subtotal:string;vatTotal:string;grandTotal:string;status:string;eDocumentType?:string;eDocumentStatus?:string;accountingReady?:boolean;externalProvider:string|null;externalId:string|null;externalNo:string|null;lastSyncAt:string|null;syncError:string|null;notes:string|null;itemCount?:number;items?:Array<{id:number;productId:number|null;description:string;quantity:string;unitPrice:string;vatRate:string;lineTotal:string;sku?:string|null;productName?:string|null;unit?:string|null}>};
export type ParasutStatus={provider:"PARASUT";configured:boolean;companyId:string|null;mode:string;baseUrl:string;defaultAccountId?:string|null};
export type VatReportRow={direction:"SALE"|"PURCHASE";subtotal:string;vatTotal:string;grandTotal:string;count:number};
export type ParasutAccountMapping={id:number;code:string;name:string;type:string;currency:string;externalAccountId:string|null;externalAccountName:string|null;mapped:boolean};
export type EDocumentReadiness={id:number;invoiceNo:string;direction:string;sourceType:string;status:string;eDocumentType:string;eDocumentStatus:string;partyName:string|null;taxNumber:string|null;address:string|null;city:string|null;ready:boolean};

export type RentalItem={id:number;rentalId:number;deviceId:number;serialNumber:string;deviceStatus:string;productName:string;sku:string;checkoutCondition:string|null;returnCondition:string|null;checkoutAccessories:string|null;returnAccessories:string|null;deliveredAt:string|null;returnedAt:string|null;damageCharge:string;notes:string|null};
export type RentalHistory={id:number;rentalId:number;fromStatus:string|null;toStatus:string;note:string|null;changedBy:number|null;changedByName:string|null;createdAt:string};
export type RentalAgreement={id:number;rentalNo:string;customerId:number;customerName:string;type:string;status:string;billingPeriod:string;startDate:string;plannedReturnDate:string|null;actualReturnDate:string|null;dailyRate:string;monthlyRate:string;fixedAmount:string;depositAmount:string;depositStatus:string;currency:string;deliveryAddress:string|null;contactName:string|null;contactPhone:string|null;notes:string|null;deviceCount?:number;devices?:string;items?:RentalItem[];history?:RentalHistory[]};
export type RentalSummary={active:number;overdue:number;reserved:number;heldDeposits:string;demos:number};
export type RentalBilling={days:number;months:number;rentalAmount:number;damageCharge:number;total:number;currency:string};
export type RentalDevice={id:number;serialNumber:string;status:string;productId:number;productName:string;sku:string;category:string|null};
export type MaintenanceSummary={maintenanceDue30:number;maintenanceOverdue:number;calibrationDue30:number;calibrationOverdue:number;inMaintenance:number;certificatesExpiring30:number};
export type DeviceMaintenanceRecord={id:number;maintenanceNo:string;deviceId:number;serialNumber:string;productName:string;customerName:string|null;type:string;status:string;scheduledDate:string|null;startedAt:string|null;completedAt:string|null;provider:string|null;technician:string|null;description:string|null;result:string|null;cost:string;currency:string;nextDueDate:string|null;serviceRecordId:number|null;rentalId:number|null;createdAt:string;updatedAt:string};
export type DeviceCalibrationRecord={id:number;calibrationNo:string;deviceId:number;serialNumber:string;productName:string;customerName:string|null;status:string;scheduledDate:string|null;calibratedAt:string|null;validUntil:string|null;provider:string|null;technician:string|null;standardReference:string|null;result:string|null;notes:string|null;cost:string;currency:string;createdAt:string;updatedAt:string};
export type DeviceCertificate={id:number;deviceId:number;serialNumber:string;productName:string;calibrationId:number|null;type:string;certificateNo:string;issuer:string|null;issuedAt:string|null;validUntil:string|null;fileName:string|null;fileUrl:string|null;notes:string|null;createdAt:string};
export type DeviceMaintenanceDetail=InventoryDevice & {lastMaintenanceAt?:string|null;nextMaintenanceAt?:string|null;lastCalibrationAt?:string|null;nextCalibrationAt?:string|null;maintenanceIntervalMonths?:number|null;calibrationIntervalMonths?:number|null;maintenance:DeviceMaintenanceRecord[];calibrations:DeviceCalibrationRecord[];certificates:DeviceCertificate[]};

export type DocumentCategory={id:number;code:string;name:string;description:string|null};
export type DocumentVersion={id:number;documentId:number;versionNo:number;fileName:string;storageKey:string;mimeType:string|null;fileSize:number|string;sha256:string|null;changeNote:string|null;uploadedBy:number|null;uploadedByName?:string|null;createdAt:string};
export type DocumentLink={id:number;documentId:number;entityType:string;entityId:number;label:string|null;createdAt:string};
export type DocumentAudit={id:number;documentId:number;versionId:number|null;action:string;userId:number|null;username?:string|null;metadata:any;createdAt:string};
export type ErpDocument={id:number;documentNo:string;title:string;description:string|null;categoryId:number|null;categoryCode:string|null;categoryName:string|null;status:string;accessLevel:string;ownerUserId:number|null;ownerUsername:string|null;currentVersionId:number|null;fileName:string|null;mimeType:string|null;fileSize:number|string|null;versionNo:number|null;createdAt:string;updatedAt:string;versions?:DocumentVersion[];links?:DocumentLink[];audit?:DocumentAudit[];accessRules?:Array<{id:number;roleCode:string|null;userId:number|null;canView:boolean;canEdit:boolean}>};
export type DocumentSummary={total:number;active:number;restricted:number;versions:number;bytes:number|string};
export type IntegrationSyncLog={id:number;provider:string;action:string;entityType:string|null;localId:number|null;externalId:string|null;status:"SUCCESS"|"ERROR"|"SKIPPED";message:string|null;createdAt:string};


export const api={
  globalSearch:(q:string)=>apiFetch<GlobalSearchResult[]>(`/search?q=${encodeURIComponent(q)}`),
  documentSummary:()=>apiFetch<DocumentSummary>("/documents/summary"),documentCategories:()=>apiFetch<DocumentCategory[]>("/documents/categories"),documents:(q?:string,category?:string,entityType?:string,entityId?:string)=>{const p=new URLSearchParams();if(q)p.set("q",q);if(category)p.set("category",category);if(entityType)p.set("entityType",entityType);if(entityId)p.set("entityId",entityId);return apiFetch<ErpDocument[]>(`/documents${p.toString()?`?${p}`:""}`)},document:(id:string)=>apiFetch<ErpDocument>(`/documents/${encodeURIComponent(id)}`),createDocument:(input:Record<string,unknown>)=>apiFetch<ErpDocument>("/documents",{method:"POST",body:JSON.stringify(input)}),addDocumentLink:(id:string,input:Record<string,unknown>)=>apiFetch<DocumentLink>(`/documents/${encodeURIComponent(id)}/links`,{method:"POST",body:JSON.stringify(input)}),removeDocumentLink:(id:string,linkId:string)=>apiFetch(`/documents/${encodeURIComponent(id)}/links/${encodeURIComponent(linkId)}`,{method:"DELETE"}),updateDocumentStatus:(id:string,status:string)=>apiFetch<ErpDocument>(`/documents/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify({status})}),saveDocumentAccess:(id:string,rules:any[])=>apiFetch(`/documents/${encodeURIComponent(id)}/access`,{method:"PUT",body:JSON.stringify({rules})}),uploadDocumentVersion:async(id:string,file:File,changeNote?:string)=>{const headers=new Headers();headers.set("Content-Type",file.type||"application/octet-stream");headers.set("X-File-Name",file.name);if(changeNote)headers.set("X-Change-Note",changeNote);if(authToken)headers.set("Authorization",`Bearer ${authToken}`);const r=await fetch(`${API_URL}/documents/${encodeURIComponent(id)}/versions/upload`,{method:"POST",headers,body:file,cache:"no-store"});const b=await r.json().catch(()=>null);if(!r.ok)throw new ApiError(r.status,b?.message||"Dosya yÃ¼klenemedi.");return (b?.data??b) as DocumentVersion},downloadDocumentVersion:async(id:string)=>{const h=new Headers();if(authToken)h.set("Authorization",`Bearer ${authToken}`);const r=await fetch(`${API_URL}/documents/versions/${encodeURIComponent(id)}/download`,{headers:h,cache:"no-store"});if(!r.ok){const b=await r.json().catch(()=>null);throw new ApiError(r.status,b?.message||"Dosya indirilemedi.")}return r.blob()},
  maintenanceSummary:()=>apiFetch<MaintenanceSummary>("/maintenance/summary"),maintenanceDue:(kind?:string,days=30)=>apiFetch<DeviceMaintenanceDetail[]>(`/maintenance/due?${new URLSearchParams({...(kind?{kind}:{}),days:String(days)})}`),maintenanceRecords:(deviceId?:string,status?:string)=>{const p=new URLSearchParams();if(deviceId)p.set("deviceId",deviceId);if(status)p.set("status",status);return apiFetch<DeviceMaintenanceRecord[]>(`/maintenance/records${p.toString()?`?${p}`:""}`)},maintenanceRecord:(id:string)=>apiFetch<DeviceMaintenanceRecord>(`/maintenance/records/${encodeURIComponent(id)}`),createMaintenanceRecord:(input:Record<string,unknown>)=>apiFetch<DeviceMaintenanceRecord>("/maintenance/records",{method:"POST",body:JSON.stringify(input)}),updateMaintenanceStatus:(id:string,input:Record<string,unknown>)=>apiFetch<DeviceMaintenanceRecord>(`/maintenance/records/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify(input)}),calibrations:(deviceId?:string)=>apiFetch<DeviceCalibrationRecord[]>(`/maintenance/calibrations${deviceId?`?deviceId=${encodeURIComponent(deviceId)}`:""}`),createCalibration:(input:Record<string,unknown>)=>apiFetch<DeviceCalibrationRecord>("/maintenance/calibrations",{method:"POST",body:JSON.stringify(input)}),completeCalibration:(id:string,input:Record<string,unknown>)=>apiFetch<DeviceCalibrationRecord>(`/maintenance/calibrations/${encodeURIComponent(id)}/complete`,{method:"PATCH",body:JSON.stringify(input)}),certificates:(deviceId?:string)=>apiFetch<DeviceCertificate[]>(`/maintenance/certificates${deviceId?`?deviceId=${encodeURIComponent(deviceId)}`:""}`),createCertificate:(input:Record<string,unknown>)=>apiFetch<DeviceCertificate>("/maintenance/certificates",{method:"POST",body:JSON.stringify(input)}),deviceMaintenance:(id:string)=>apiFetch<DeviceMaintenanceDetail>(`/maintenance/devices/${encodeURIComponent(id)}`),updateDeviceMaintenanceSchedule:(id:string,input:Record<string,unknown>)=>apiFetch(`/maintenance/devices/${encodeURIComponent(id)}/schedule`,{method:"PATCH",body:JSON.stringify(input)}),syncMaintenanceNotifications:()=>apiFetch("/maintenance/notifications/sync",{method:"POST"}),


  rentals:(status?:string,customerId?:string)=>{const p=new URLSearchParams();if(status)p.set("status",status);if(customerId)p.set("customerId",customerId);return apiFetch<RentalAgreement[]>(`/rentals${p.toString()?`?${p}`:""}`)},rentalSummary:()=>apiFetch<RentalSummary>("/rentals/summary"),rentalAvailableDevices:()=>apiFetch<RentalDevice[]>("/rentals/available-devices"),rental:(id:string)=>apiFetch<RentalAgreement>(`/rentals/${encodeURIComponent(id)}`),rentalBilling:(id:string)=>apiFetch<RentalBilling>(`/rentals/${encodeURIComponent(id)}/billing-preview`),createRental:(input:Record<string,unknown>)=>apiFetch<RentalAgreement>("/rentals",{method:"POST",body:JSON.stringify(input)}),deliverRental:(id:string,input:Record<string,unknown>)=>apiFetch<RentalAgreement>(`/rentals/${encodeURIComponent(id)}/deliver`,{method:"POST",body:JSON.stringify(input)}),returnRental:(id:string,input:Record<string,unknown>)=>apiFetch<RentalAgreement>(`/rentals/${encodeURIComponent(id)}/return`,{method:"POST",body:JSON.stringify(input)}),cancelRental:(id:string)=>apiFetch<RentalAgreement>(`/rentals/${encodeURIComponent(id)}/cancel`,{method:"POST"}),updateRentalDeposit:(id:string,status:string)=>apiFetch<RentalAgreement>(`/rentals/${encodeURIComponent(id)}/deposit`,{method:"PATCH",body:JSON.stringify({status})}),
  health:()=>apiFetch<{success:boolean;message:string}>("/health"),
  tasks:(scope="mine",status?:string,q?:string)=>{const p=new URLSearchParams();if(scope)p.set("scope",scope);if(status)p.set("status",status);if(q)p.set("q",q);return apiFetch<WorkTask[]>(`/tasks?${p}`)},taskSummary:()=>apiFetch<WorkTaskSummary>("/tasks/summary"),task:(id:string)=>apiFetch<WorkTask>(`/tasks/${encodeURIComponent(id)}`),taskAssignees:()=>apiFetch<TaskAssignee[]>("/tasks/assignees"),createTask:(input:Record<string,unknown>)=>apiFetch<WorkTask>("/tasks",{method:"POST",body:JSON.stringify(input)}),updateTask:(id:string,input:Record<string,unknown>)=>apiFetch<WorkTask>(`/tasks/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(input)}),

  login:(identifier:string,password:string)=>apiFetch<{token:string;user:CurrentUser}>("/auth/login",{method:"POST",body:JSON.stringify({identifier,password})}),
  me:()=>apiFetch<CurrentUser>("/auth/me"),logout:()=>apiFetch("/auth/logout",{method:"POST"}),dashboard:()=>apiFetch("/dashboard/summary"),
  customers:(query?:string)=>apiFetch<Customer[]>(`/customers${query?`?q=${encodeURIComponent(query)}`:""}`),customer:(id:string)=>apiFetch<Customer>(`/customers/${encodeURIComponent(id)}`),createCustomer:(input:CustomerInput)=>apiFetch<Customer>("/customers",{method:"POST",body:JSON.stringify(input)}),updateCustomer:(id:string,input:Partial<CustomerInput>)=>apiFetch<Customer>(`/customers/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(input)}),
  services:(status?:string)=>apiFetch<ServiceRecord[]>(`/service-records${status?`?status=${encodeURIComponent(status)}`:""}`),service:(id:string)=>apiFetch<ServiceRecord>(`/service-records/${encodeURIComponent(id)}`),createService:(input:Record<string,unknown>)=>apiFetch<ServiceRecord>("/service-records",{method:"POST",body:JSON.stringify(input)}),updateServiceStatus:(id:string,status:string,note?:string)=>apiFetch<ServiceRecord>(`/service-records/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify({status,note})}),addServiceOperation:(id:string,input:{type:string;description:string;laborMinutes:number;amount:number})=>apiFetch<ServiceOperation>(`/service-records/${encodeURIComponent(id)}/operations`,{method:"POST",body:JSON.stringify(input)}),addServicePart:(id:string,input:{productId:number;quantity:number;unitPrice?:number})=>apiFetch<ServicePart>(`/service-records/${encodeURIComponent(id)}/parts`,{method:"POST",body:JSON.stringify(input)}),updateServiceBilling:(id:string,input:Record<string,unknown>)=>apiFetch<ServiceRecord>(`/service-records/${encodeURIComponent(id)}/billing`,{method:"PATCH",body:JSON.stringify(input)}),
  projectCompanies:()=>apiFetch<GroupCompany[]>("/projects/companies"),projectSummary:()=>apiFetch<ProjectSummary>("/projects/summary"),projects:(status?:string,type?:string,q?:string)=>{const p=new URLSearchParams();if(status)p.set("status",status);if(type)p.set("type",type);if(q)p.set("q",q);return apiFetch<ErpProject[]>(`/projects${p.toString()?`?${p}`:""}`)},project:(id:string)=>apiFetch<ErpProject>(`/projects/${encodeURIComponent(id)}`),createProject:(input:Record<string,unknown>)=>apiFetch<ErpProject>("/projects",{method:"POST",body:JSON.stringify(input)}),createProjectTask:(id:string,input:Record<string,unknown>)=>apiFetch<ProjectTask>(`/projects/${encodeURIComponent(id)}/tasks`,{method:"POST",body:JSON.stringify(input)}),updateProjectTask:(taskId:string,input:Record<string,unknown>)=>apiFetch<ProjectTask>(`/projects/tasks/${encodeURIComponent(taskId)}`,{method:"PATCH",body:JSON.stringify(input)}),addProjectAssignment:(id:string,input:Record<string,unknown>)=>apiFetch<ProjectAssignment>(`/projects/${encodeURIComponent(id)}/assignments`,{method:"POST",body:JSON.stringify(input)}),addProjectMilestone:(id:string,input:Record<string,unknown>)=>apiFetch<ProjectMilestone>(`/projects/${encodeURIComponent(id)}/milestones`,{method:"POST",body:JSON.stringify(input)}),
  supportTickets:(customerId?:string,status?:string,q?:string)=>{const p=new URLSearchParams();if(customerId)p.set("customerId",customerId);if(status)p.set("status",status);if(q)p.set("q",q);return apiFetch<SupportTicket[]>(`/support/tickets${p.toString()?`?${p}`:""}`)},supportSummary:()=>apiFetch<SupportSummary>("/support/tickets/summary"),supportAgents:()=>apiFetch<CurrentUser[]>("/support/agents"),supportTicket:(id:string)=>apiFetch<SupportTicket>(`/support/tickets/${encodeURIComponent(id)}`),createSupportTicket:(input:Record<string,unknown>)=>apiFetch<SupportTicket>("/support/tickets",{method:"POST",body:JSON.stringify(input)}),addSupportComment:(id:string,input:{body:string;visibility?:string;type?:string})=>apiFetch<SupportTicketComment>(`/support/tickets/${encodeURIComponent(id)}/comments`,{method:"POST",body:JSON.stringify(input)}),updateSupportStatus:(id:string,status:string,resolution?:string)=>apiFetch<SupportTicket>(`/support/tickets/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify({status,resolution})}),assignSupportTicket:(id:string,assignedUserId:number|null,department?:string)=>apiFetch<SupportTicket>(`/support/tickets/${encodeURIComponent(id)}/assignment`,{method:"PATCH",body:JSON.stringify({assignedUserId,department})}),
  corsStations:(status?:string)=>apiFetch(`/cors/stations${status?`?status=${encodeURIComponent(status)}`:""}`),corsSummary:()=>apiFetch("/cors/summary"),
  corsPackages:()=>apiFetch<CorsPackage[]>("/cors/packages"),corsSubscriptions:(customerId?:string,status?:string,expiringDays?:number)=>{const p=new URLSearchParams();if(customerId)p.set("customerId",customerId);if(status)p.set("status",status);if(expiringDays)p.set("expiringDays",String(expiringDays));return apiFetch<CorsSubscription[]>(`/cors/subscriptions${p.toString()?`?${p}`:""}`)},corsSubscription:(id:string)=>apiFetch<CorsSubscription>(`/cors/subscriptions/${encodeURIComponent(id)}`),corsSubscriptionSummary:()=>apiFetch<CorsSubscriptionSummary>("/cors/subscriptions/summary"),createCorsSubscription:(input:Record<string,unknown>)=>apiFetch<CorsSubscription>("/cors/subscriptions",{method:"POST",body:JSON.stringify(input)}),renewCorsSubscription:(id:string,input:Record<string,unknown>)=>apiFetch<CorsSubscription>(`/cors/subscriptions/${encodeURIComponent(id)}/renew`,{method:"POST",body:JSON.stringify(input)}),updateCorsPayment:(id:string,paymentStatus:string)=>apiFetch<CorsSubscription>(`/cors/subscriptions/${encodeURIComponent(id)}/payment`,{method:"PATCH",body:JSON.stringify({paymentStatus})}),
  corsEvents:(stationId?:string)=>apiFetch<CorsStationEvent[]>(`/cors/events${stationId?`?stationId=${encodeURIComponent(stationId)}`:""}`),createCorsEvent:(input:Record<string,unknown>)=>apiFetch<CorsStationEvent>("/cors/events",{method:"POST",body:JSON.stringify(input)}),corsMaintenance:(status?:string)=>apiFetch<CorsMaintenance[]>(`/cors/maintenance${status?`?status=${encodeURIComponent(status)}`:""}`),createCorsMaintenance:(input:Record<string,unknown>)=>apiFetch<CorsMaintenance>("/cors/maintenance",{method:"POST",body:JSON.stringify(input)}),updateCorsMaintenanceStatus:(id:string,status:string)=>apiFetch<CorsMaintenance>(`/cors/maintenance/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify({status})}),corsUptime:(days=30)=>apiFetch<CorsUptime[]>(`/cors/reports/uptime?days=${days}`),corsRevenue:(months=12)=>apiFetch<CorsRevenue[]>(`/cors/reports/revenue?months=${months}`),notifications:()=>apiFetch<AppNotification[]>("/notifications"),notificationSummary:()=>apiFetch<NotificationSummary>("/notifications/summary"),readNotification:(id:string)=>apiFetch<AppNotification>(`/notifications/${encodeURIComponent(id)}/read`,{method:"PATCH"}),readAllNotifications:()=>apiFetch("/notifications/read-all",{method:"POST"}),users:()=>apiFetch<CurrentUser[]>("/users"),roles:()=>apiFetch<{code:string;permissions:string[]}[]>("/roles"),createUser:(x:any)=>apiFetch<CurrentUser>("/users",{method:"POST",body:JSON.stringify(x)}),updateUser:(id:number,x:any)=>apiFetch<CurrentUser>(`/users/${id}`,{method:"PATCH",body:JSON.stringify(x)}),changeUserPassword:(id:number,password:string)=>apiFetch(`/users/${id}/password`,{method:"PATCH",body:JSON.stringify({password})}),
  financeSummary:()=>apiFetch<FinanceSummary>("/finance/summary"),financeCustomerRisk:(id:string,proposedAmount=0)=>apiFetch<CustomerRisk>(`/finance/risk/customers/${encodeURIComponent(id)}?proposedAmount=${encodeURIComponent(String(proposedAmount))}`),financeReceivableAging:()=>apiFetch<ReceivableAging[]>("/finance/reports/receivable-aging"),syncFinanceRiskNotifications:()=>apiFetch("/finance/risk/notifications/sync",{method:"POST"}),financeDocuments:(direction?:string,partyType?:string,status?:string)=>{const p=new URLSearchParams();if(direction)p.set("direction",direction);if(partyType)p.set("partyType",partyType);if(status)p.set("status",status);return apiFetch<FinanceDocument[]>(`/finance/documents${p.toString()?`?${p}`:""}`)},financeAccounts:()=>apiFetch<FinanceAccount[]>("/finance/accounts"),createFinanceAccount:(input:Record<string,unknown>)=>apiFetch<FinanceAccount>("/finance/accounts",{method:"POST",body:JSON.stringify(input)}),financeTransactions:()=>apiFetch<FinanceTransaction[]>("/finance/transactions"),settleFinanceDocument:(id:string,input:Record<string,unknown>)=>apiFetch<FinanceTransaction>(`/finance/documents/${encodeURIComponent(id)}/settle`,{method:"POST",body:JSON.stringify(input)}),financeCustomerLedger:(id:string)=>apiFetch<FinanceLedger>(`/finance/customers/${encodeURIComponent(id)}`),financeSupplierLedger:(id:string)=>apiFetch<FinanceLedger>(`/finance/suppliers/${encodeURIComponent(id)}`),syncFinance:()=>apiFetch("/finance/sync",{method:"POST"}),
  financeInvoices:(direction?:string,status?:string)=>{const p=new URLSearchParams();if(direction)p.set("direction",direction);if(status)p.set("status",status);return apiFetch<CommercialInvoice[]>(`/finance/invoices${p.toString()?`?${p}`:""}`)},financeInvoice:(id:string)=>apiFetch<CommercialInvoice>(`/finance/invoices/${encodeURIComponent(id)}`),syncInvoiceSources:()=>apiFetch("/finance/invoices/sync-sources",{method:"POST"}),pushInvoiceToParasut:(id:string)=>apiFetch(`/finance/invoices/${encodeURIComponent(id)}/push-parasut`,{method:"POST"}),parasutStatus:()=>apiFetch<ParasutStatus>("/finance/integrations/parasut/status"),testParasut:()=>apiFetch("/finance/integrations/parasut/test",{method:"POST"}),parasutLogs:()=>apiFetch<IntegrationSyncLog[]>("/finance/integrations/parasut/logs"),pushFinanceTransactionToParasut:(id:string)=>apiFetch(`/finance/transactions/${encodeURIComponent(id)}/push-parasut`,{method:"POST"}),financeVatReport:(from?:string,to?:string)=>{const p=new URLSearchParams();if(from)p.set("from",from);if(to)p.set("to",to);return apiFetch<VatReportRow[]>(`/finance/reports/vat${p.toString()?`?${p}`:""}`)},parasutAccountMappings:()=>apiFetch<ParasutAccountMapping[]>("/finance/integrations/parasut/account-mappings"),saveParasutAccountMapping:(id:string,input:{externalAccountId:string;externalAccountName?:string})=>apiFetch(`/finance/integrations/parasut/account-mappings/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(input)}),eDocumentReadiness:()=>apiFetch<EDocumentReadiness[]>("/finance/e-documents/readiness"),
  suppliers:(q?:string)=>apiFetch<Supplier[]>(`/suppliers${q?`?q=${encodeURIComponent(q)}`:""}`),createSupplier:(input:Record<string,unknown>)=>apiFetch<Supplier>("/suppliers",{method:"POST",body:JSON.stringify(input)}),
  purchaseRequests:()=>apiFetch<PurchaseRequest[]>("/purchase-requests"),createPurchaseRequest:(input:Record<string,unknown>)=>apiFetch<PurchaseRequest>("/purchase-requests",{method:"POST",body:JSON.stringify(input)}),updatePurchaseRequestStatus:(id:string,status:string)=>apiFetch<PurchaseRequest>(`/purchase-requests/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify({status})}),
  supplierQuotes:()=>apiFetch<SupplierQuote[]>("/supplier-quotes"),createSupplierQuote:(input:Record<string,unknown>)=>apiFetch<SupplierQuote>("/supplier-quotes",{method:"POST",body:JSON.stringify(input)}),selectSupplierQuote:(id:string)=>apiFetch<SupplierQuote>(`/supplier-quotes/${encodeURIComponent(id)}/select`,{method:"PATCH"}),convertSupplierQuoteToOrder:(id:string)=>apiFetch<PurchaseOrder>(`/supplier-quotes/${encodeURIComponent(id)}/convert-to-order`,{method:"POST"}),
  purchaseOrders:()=>apiFetch<PurchaseOrder[]>("/purchase-orders"),purchaseOrder:(id:string)=>apiFetch<PurchaseOrder>(`/purchase-orders/${encodeURIComponent(id)}`),createPurchaseOrder:(input:Record<string,unknown>)=>apiFetch<PurchaseOrder>("/purchase-orders",{method:"POST",body:JSON.stringify(input)}),receivePurchaseOrder:(id:string,input:Record<string,unknown>)=>apiFetch(`/purchase-orders/${encodeURIComponent(id)}/receive`,{method:"POST",body:JSON.stringify(input)}),criticalStock:()=>apiFetch<Product[]>("/purchasing/critical-stock"),
  products:(query?:string)=>apiFetch<Product[]>(`/products${query?`?q=${encodeURIComponent(query)}`:""}`),product:(id:string)=>apiFetch<Product>(`/products/${encodeURIComponent(id)}`),createProduct:(input:Record<string,unknown>)=>apiFetch<Product>("/products",{method:"POST",body:JSON.stringify(input)}),
  devices:(productId?:string,customerId?:string)=>{const p=new URLSearchParams();if(productId)p.set("productId",productId);if(customerId)p.set("customerId",customerId);return apiFetch<InventoryDevice[]>(`/inventory/devices${p.toString()?`?${p}`:""}`)},device:(id:string)=>apiFetch<InventoryDevice>(`/inventory/devices/${encodeURIComponent(id)}`),createDevice:(productId:number,serialNumber:string)=>apiFetch<InventoryDevice>("/inventory/devices",{method:"POST",body:JSON.stringify({productId,serialNumber})}),stockMovements:(productId?:string,deviceId?:string)=>{const p=new URLSearchParams();if(productId)p.set("productId",productId);if(deviceId)p.set("deviceId",deviceId);return apiFetch<StockMovement[]>(`/stock/movements${p.toString()?`?${p}`:""}`)},
  quotes:(customerId?:string)=>apiFetch<Quote[]>(`/quotes${customerId?`?customerId=${encodeURIComponent(customerId)}`:""}`),quote:(id:string)=>apiFetch<Quote>(`/quotes/${encodeURIComponent(id)}`),createQuote:(input:Record<string,unknown>)=>apiFetch<Quote>("/quotes",{method:"POST",body:JSON.stringify(input)}),updateQuoteStatus:(id:string,status:string)=>apiFetch<Quote>(`/quotes/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify({status})}),convertQuoteToOrder:(id:string)=>apiFetch<SalesOrder>(`/quotes/${encodeURIComponent(id)}/convert-to-order`,{method:"POST"}),
  orders:(customerId?:string)=>apiFetch<SalesOrder[]>(`/orders${customerId?`?customerId=${encodeURIComponent(customerId)}`:""}`),order:(id:string)=>apiFetch<SalesOrder>(`/orders/${encodeURIComponent(id)}`),deliverOrder:(
  id:string,
  input:{
    deliveryNote?:string;
    warrantyMonths?:number;
    deviceIds?:number[];
  }
)=>apiFetch<SalesOrder>(
  `/orders/${encodeURIComponent(id)}/deliver`,
  {
    method:"POST",
    body:JSON.stringify(input)
  }
),
  auditLogs:(params?:Record<string,string>)=>{const p=new URLSearchParams(params);return apiFetch<{items:any[];total:number;limit:number;offset:number}>(`/audit${p.toString()?`?${p}`:""}`)},
  auditSummary:()=>apiFetch<{today:number;week:number;users:number}>("/audit/summary"),
  executiveDashboard:()=>apiFetch<any>("/dashboard/summary"),
  organizationSummary:()=>apiFetch<any>("/organization/summary"),
  organizationCompanies:()=>apiFetch<any[]>("/organization/companies"),
  organizationDepartments:()=>apiFetch<any[]>("/organization/departments"),
  organizationEmployees:(q?:string)=>apiFetch<any[]>(`/organization/employees${q?`?q=${encodeURIComponent(q)}`:""}`),
  organizationEmployee:(id:string)=>apiFetch<any>(`/organization/employees/${id}`),
  createEmployee:(x:any)=>apiFetch<any>("/organization/employees",{method:"POST",body:JSON.stringify(x)}),
  assignEmployee:(id:string,x:any)=>apiFetch<any>(`/organization/employees/${id}/assignments`,{method:"POST",body:JSON.stringify(x)}),
  hrSummary:()=>apiFetch<any>("/organization/hr/summary"),
  employeeAvailability:(id:string,startDate:string,endDate:string)=>apiFetch<any>(`/organization/employees/${id}/availability?startDate=${startDate}&endDate=${endDate}`),
  employeeLeaves:(id:string)=>apiFetch<any[]>(`/organization/employees/${id}/leaves`),
  createEmployeeLeave:(id:string,x:any)=>apiFetch<any>(`/organization/employees/${id}/leaves`,{method:"POST",body:JSON.stringify(x)}),
  employeeCertifications:(id:string)=>apiFetch<any[]>(`/organization/employees/${id}/certifications`),
  createEmployeeCertification:(id:string,x:any)=>apiFetch<any>(`/organization/employees/${id}/certifications`,{method:"POST",body:JSON.stringify(x)}),
  employeeTrainings:(id:string)=>apiFetch<any[]>(`/organization/employees/${id}/trainings`),
  createEmployeeTraining:(id:string,x:any)=>apiFetch<any>(`/organization/employees/${id}/trainings`,{method:"POST",body:JSON.stringify(x)}),
  fieldOperations:(from:string,to:string)=>apiFetch<any[]>(`/field-operations?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`),
  fieldSummary:()=>apiFetch<any>("/field-operations/summary"),
  fieldAvailableEmployees:(startAt:string,endAt:string)=>apiFetch<any[]>(`/field-operations/available-employees?startAt=${encodeURIComponent(startAt)}&endAt=${encodeURIComponent(endAt)}`),
  createFieldOperation:(x:any)=>apiFetch<any>("/field-operations",{method:"POST",body:JSON.stringify(x)}),
  fieldResources:()=>apiFetch<any[]>("/field-resources"),
  fieldResourceSummary:()=>apiFetch<any>("/field-resources/summary"),
  fieldAvailableResources:(startAt:string,endAt:string)=>apiFetch<any[]>(`/field-resources/available?startAt=${encodeURIComponent(startAt)}&endAt=${encodeURIComponent(endAt)}`),
  createFieldResource:(x:any)=>apiFetch<any>("/field-resources",{method:"POST",body:JSON.stringify(x)}),
  fieldExpenses:()=>apiFetch<any[]>("/field-expenses"),
  fieldExpenseSummary:()=>apiFetch<any>("/field-expenses/summary"),
  createFieldExpense:(x:any)=>apiFetch<any>("/field-expenses",{method:"POST",body:JSON.stringify(x)}),
  setFieldExpenseStatus:(id:number,status:string)=>apiFetch<any>(`/field-expenses/${id}/status`,{method:"PATCH",body:JSON.stringify({status})}),
  projectCostSummary:(id:string)=>apiFetch<any>(`/projects/${id}/cost-summary`),
  permissions:()=>apiFetch<any[]>("/permissions"),
  createRole:(x:any)=>apiFetch<any>("/roles",{method:"POST",body:JSON.stringify(x)}),
  setRolePermissions:(code:string,permissions:string[])=>apiFetch<any>(`/roles/${encodeURIComponent(code)}/permissions`,{method:"PUT",body:JSON.stringify({permissions})}),
  setRoleStatus:(code:string,isActive:boolean)=>apiFetch<any>(`/roles/${encodeURIComponent(code)}/status`,{method:"PATCH",body:JSON.stringify({isActive})}),
  crmSummary:()=>apiFetch<any>("/crm/summary"),
  crmActivities:(customerId?:number)=>apiFetch<any[]>(`/crm/activities${customerId?`?customerId=${customerId}`:""}`),
  crmFollowUps:(mine=false)=>apiFetch<any[]>(`/crm/follow-ups${mine?"?mine=1":""}`),
  customerTimeline:(id:number|string)=>apiFetch<any[]>(`/customers/${id}/timeline`),
  createCrmActivity:(x:any)=>apiFetch<any>("/crm/activities",{method:"POST",body:JSON.stringify(x)}),
  createCustomerNote:(id:number|string,x:any)=>apiFetch<any>(`/customers/${id}/notes`,{method:"POST",body:JSON.stringify(x)}),
  reportingAnalytics:(months=12)=>apiFetch<any>(`/reports/analytics?months=${months}`),
  reportingTopCustomers:(limit=10)=>apiFetch<any[]>(`/reports/top-customers?limit=${limit}`),
  reportingProjectProfitability:()=>apiFetch<any[]>("/reports/project-profitability"),
  parasutQueue:(status?:string)=>apiFetch<any[]>(`/finance/integrations/parasut/queue${status?`?status=${encodeURIComponent(status)}`:""}`),
  parasutQueueSummary:()=>apiFetch<any>("/finance/integrations/parasut/queue-summary"),
  processParasutQueue:(limit=10)=>apiFetch<any>("/finance/integrations/parasut/queue/process",{method:"POST",body:JSON.stringify({limit})}),
  retryParasutQueueJob:(id:number|string)=>apiFetch<any>(`/finance/integrations/parasut/queue/${id}/retry`,{method:"POST"}),
  queueInvoiceToParasut:(id:number|string)=>apiFetch<any>(`/finance/invoices/${id}/queue-parasut`,{method:"POST"}),
  queueFinanceTransactionToParasut:(id:number|string)=>apiFetch<any>(`/finance/transactions/${id}/queue-parasut`,{method:"POST"}),
  communicationSummary:()=>apiFetch<any>("/communications/summary"),
  communicationOutbox:()=>apiFetch<any[]>("/communications/outbox"),
  communicationTemplates:()=>apiFetch<any[]>("/communications/templates"),
  enqueueCommunication:(x:any)=>apiFetch<any>("/communications/outbox",{method:"POST",body:JSON.stringify(x)}),
  retryCommunication:(id:number|string)=>apiFetch<any>(`/communications/outbox/${id}/retry`,{method:"POST"}),
};
