import{pool,query}from"../db/pool.js";
export async function templates(){return(await query(`SELECT * FROM "communicationTemplate" ORDER BY channel,name`)).rows}
export async function outbox(limit=100){return(await query(`SELECT * FROM "communicationOutbox" ORDER BY "createdAt" DESC LIMIT $1`,[Math.min(limit,500)])).rows}
export async function enqueue(x:any,userId?:number){return(await query(`INSERT INTO "communicationOutbox"(channel,recipient,subject,body,"templateCode","entityType","entityId","dedupeKey","createdBy") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT("dedupeKey") DO UPDATE SET "dedupeKey"=EXCLUDED."dedupeKey" RETURNING *`,[x.channel,x.recipient,x.subject||null,x.body,x.templateCode||null,x.entityType||null,x.entityId||null,x.dedupeKey||null,userId||null])).rows[0]}
export async function summary(){return(await query(`SELECT COUNT(*) FILTER(WHERE status IN('PENDING','RETRY'))::int pending,COUNT(*) FILTER(WHERE status='SENT')::int sent,COUNT(*) FILTER(WHERE status='FAILED')::int failed FROM "communicationOutbox"`)).rows[0]}
export async function retry(id:number){return(await query(`UPDATE "communicationOutbox" SET status='PENDING',"nextAttemptAt"=NOW(),"lastError"=NULL WHERE id=$1 AND status='FAILED' RETURNING *`,[id])).rows[0]}
export async function claim(limit=10){const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query(`SELECT * FROM "communicationOutbox" WHERE status IN('PENDING','RETRY') AND "nextAttemptAt"<=NOW() ORDER BY id FOR UPDATE SKIP LOCKED LIMIT $1`,[limit]);if(r.rows.length)await c.query(`UPDATE "communicationOutbox" SET status='PROCESSING',attempts=attempts+1 WHERE id=ANY($1::bigint[])`,[r.rows.map((x:any)=>x.id)]);await c.query('COMMIT');return r.rows} catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
export async function sent(id:number,providerMessageId?:string){await query(`UPDATE "communicationOutbox" SET status='SENT',"sentAt"=NOW(),"providerMessageId"=$2,"lastError"=NULL WHERE id=$1`,[id,providerMessageId||null])}
export async function failed(id:number,error:string){await query(`UPDATE "communicationOutbox" SET status=CASE WHEN attempts>="maxAttempts" THEN 'FAILED' ELSE 'RETRY' END,"lastError"=$2,"nextAttemptAt"=NOW()+LEAST(attempts*attempts,60)*INTERVAL '1 minute' WHERE id=$1`,[id,error.slice(0,2000)])}
