import { query, pool } from "../db/pool.js";
type CorsSubscriptionRow = {
  id: number;
  subscriptionNo: string;
  paymentStatus: string;
  [key: string]: unknown;
};
export async function listPackages(){return (await query(`SELECT * FROM "corsPackage" WHERE "isActive"=true ORDER BY "durationMonths", "name"`)).rows;}
export async function listSubscriptions(filters:{customerId?:number;status?:string;expiringDays?:number}={}){const where:string[]=[];const values:unknown[]=[];if(filters.customerId){values.push(filters.customerId);where.push(`s."customerId"=$${values.length}`)}if(filters.status){values.push(filters.status);where.push(`s."status"=$${values.length}`)}if(filters.expiringDays){values.push(filters.expiringDays);where.push(`s."endDate" BETWEEN CURRENT_DATE AND CURRENT_DATE + ($${values.length}::int * interval '1 day')`)}const sql=`SELECT s.*,CASE WHEN s."endDate" < CURRENT_DATE AND s."status"='ACTIVE' THEN 'EXPIRED' ELSE s."status" END AS "status",c."name" AS "customerName",p."name" AS "packageName",p."durationMonths",cs."code" AS "stationCode",GREATEST(0,(s."endDate"-CURRENT_DATE))::int AS "remainingDays" FROM "corsSubscription" s JOIN "customer" c ON c.id=s."customerId" JOIN "corsPackage" p ON p.id=s."packageId" LEFT JOIN "corsStation" cs ON cs.id=s."stationId" ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY s."endDate" ASC`;return (await query(sql,values)).rows;}
export async function getSubscription(id:number){const r=await query<CorsSubscriptionRow>(`SELECT s.*,CASE WHEN s."endDate" < CURRENT_DATE AND s."status"='ACTIVE' THEN 'EXPIRED' ELSE s."status" END AS "status",c."name" AS "customerName",p."name" AS "packageName",p."durationMonths",cs."code" AS "stationCode",(s."endDate"-CURRENT_DATE)::int AS "remainingDays" FROM "corsSubscription" s JOIN "customer" c ON c.id=s."customerId" JOIN "corsPackage" p ON p.id=s."packageId" LEFT JOIN "corsStation" cs ON cs.id=s."stationId" WHERE s.id=$1`,[id]);if(!r.rows[0])return null;const renewals=(await query(`SELECT * FROM "corsSubscriptionRenewal" WHERE "subscriptionId"=$1 ORDER BY "createdAt" DESC`,[id])).rows;return {...r.rows[0],renewals};}
export async function createSubscription(input:any){const pkg=(await query<any>(`SELECT * FROM "corsPackage" WHERE id=$1 AND "isActive"=true`,[input.packageId])).rows[0];if(!pkg)throw new Error("CORS paketi bulunamadı.");const start=input.startDate?new Date(input.startDate):new Date();const end=new Date(start);end.setMonth(end.getMonth()+Number(pkg.durationMonths));const no=`CRS-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;const r=await query(`INSERT INTO "corsSubscription" ("subscriptionNo","customerId","packageId","stationId","username","status","paymentStatus","startDate","endDate","amount","currency","notes") VALUES ($1,$2,$3,$4,$5,'ACTIVE',$6,$7,$8,$9,$10,$11) RETURNING *`,[no,input.customerId,input.packageId,input.stationId||null,input.username,input.paymentStatus||'PENDING',start.toISOString().slice(0,10),end.toISOString().slice(0,10),input.amount??pkg.price,input.currency??pkg.currency,input.notes??null]);return getSubscription(r.rows[0].id);}
export async function renewSubscription(id:number,input:any,userId?:number){const client=await pool.connect();try{await client.query('BEGIN');const current=(await client.query<any>(`SELECT s.*,p."durationMonths",p."price" FROM "corsSubscription" s JOIN "corsPackage" p ON p.id=s."packageId" WHERE s.id=$1 FOR UPDATE`,[id])).rows[0];if(!current)throw new Error("Abonelik bulunamadı.");const months=Number(input.months??current.durationMonths);const base=new Date(current.endDate)>new Date()?new Date(current.endDate):new Date();const newEnd=new Date(base);newEnd.setMonth(newEnd.getMonth()+months);await client.query(`UPDATE "corsSubscription" SET "endDate"=$2,"status"='ACTIVE',"paymentStatus"=$3,"updatedAt"=now() WHERE id=$1`,[id,newEnd.toISOString().slice(0,10),input.paymentStatus||'PENDING']);await client.query(`INSERT INTO "corsSubscriptionRenewal" ("subscriptionId","previousEndDate","newEndDate","amount","paymentStatus","note","renewedBy") VALUES ($1,$2,$3,$4,$5,$6,$7)`,[id,current.endDate,newEnd.toISOString().slice(0,10),input.amount??current.price,input.paymentStatus||'PENDING',input.note??null,userId??null]);await client.query('COMMIT');return getSubscription(id);}catch(e){await client.query('ROLLBACK');throw e}finally{client.release();}}
export async function updateSubscriptionPayment(id:number,paymentStatus:string){await query(`UPDATE "corsSubscription" SET "paymentStatus"=$2,"updatedAt"=now() WHERE id=$1`,[id,paymentStatus]);return getSubscription(id);}
export async function subscriptionSummary(){const r=await query<any>(`SELECT count(*)::int AS total,count(*) FILTER(WHERE "status"='ACTIVE' AND "endDate">=CURRENT_DATE)::int AS active,count(*) FILTER(WHERE "endDate" BETWEEN CURRENT_DATE AND CURRENT_DATE+interval '30 day')::int AS "expiring30",count(*) FILTER(WHERE "paymentStatus" IN ('PENDING','OVERDUE','PARTIAL'))::int AS "unpaid",COALESCE(sum("amount") FILTER(WHERE "status"='ACTIVE' AND "endDate">=CURRENT_DATE),0)::text AS "activeValue" FROM "corsSubscription"`);return r.rows[0];}
