import { pool, query } from "../db/pool.js";

export const documentNo=()=>`DOC-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`;

const base=`SELECT d.*,c.code AS "categoryCode",c.name AS "categoryName",u.username AS "ownerUsername",v."fileName",v."mimeType",v."fileSize",v."versionNo",v."createdAt" AS "versionCreatedAt" FROM document d LEFT JOIN "documentCategory" c ON c.id=d."categoryId" LEFT JOIN "user" u ON u.id=d."ownerUserId" LEFT JOIN "documentVersion" v ON v.id=d."currentVersionId"`;

export async function categories(){return (await query<any>(`SELECT * FROM "documentCategory" WHERE "isActive"=true ORDER BY name`)).rows}
export async function list(filters:{q?:string;category?:string;entityType?:string;entityId?:number;status?:string;userId?:number;role?:string}={}){const vals:any[]=[];const where:string[]=[];let join='';if(filters.role&&filters.role!=='ADMIN'){vals.push(filters.userId||0);const up=`$${vals.length}`;vals.push(filters.role);const rp=`$${vals.length}`;where.push(`(d."accessLevel"<>'RESTRICTED' OR d."ownerUserId"=${up} OR d."createdBy"=${up} OR EXISTS(SELECT 1 FROM "documentAccessRule" ar WHERE ar."documentId"=d.id AND ar."canView"=true AND (ar."userId"=${up} OR ar."roleCode"=${rp})))`)}if(filters.q){vals.push(`%${filters.q}%`);where.push(`(d.title ILIKE $${vals.length} OR d."documentNo" ILIKE $${vals.length} OR v."fileName" ILIKE $${vals.length})`)}if(filters.category){vals.push(filters.category);where.push(`c.code=$${vals.length}`)}if(filters.status){vals.push(filters.status);where.push(`d.status=$${vals.length}`)}if(filters.entityType&&filters.entityId){join=` JOIN "documentLink" dlq ON dlq."documentId"=d.id`;vals.push(filters.entityType);where.push(`dlq."entityType"=$${vals.length}`);vals.push(filters.entityId);where.push(`dlq."entityId"=$${vals.length}`)}return (await query<any>(`${base}${join} ${where.length?`WHERE ${where.join(' AND ')}`:''} ORDER BY d."updatedAt" DESC,d.id DESC`,vals)).rows}
export async function byId(id:number){const d=(await query<any>(`${base} WHERE d.id=$1`,[id])).rows[0];if(!d)return null;const [versions,links,audit,rules]=await Promise.all([
 query<any>(`SELECT v.*,u.username AS "uploadedByName" FROM "documentVersion" v LEFT JOIN "user" u ON u.id=v."uploadedBy" WHERE v."documentId"=$1 ORDER BY v."versionNo" DESC`,[id]),
 query<any>(`SELECT * FROM "documentLink" WHERE "documentId"=$1 ORDER BY "createdAt"`,[id]),
 query<any>(`SELECT a.*,u.username FROM "documentAudit" a LEFT JOIN "user" u ON u.id=a."userId" WHERE a."documentId"=$1 ORDER BY a."createdAt" DESC LIMIT 100`,[id]),
 query<any>(`SELECT * FROM "documentAccessRule" WHERE "documentId"=$1 ORDER BY id`,[id])]);return {...d,versions:versions.rows,links:links.rows,audit:audit.rows,accessRules:rules.rows}}
export async function create(input:any,userId?:number){const r=await query<any>(`INSERT INTO document("documentNo",title,description,"categoryId","accessLevel","ownerUserId","createdBy") VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[documentNo(),String(input.title).trim(),input.description||null,input.categoryId||null,input.accessLevel||'INTERNAL',input.ownerUserId||userId||null,userId||null]);await audit(r.rows[0].id,'CREATE',userId,{title:input.title});return r.rows[0]}
export async function addLink(documentId:number,input:any,userId?:number){const r=await query<any>(`INSERT INTO "documentLink"("documentId","entityType","entityId",label,"createdBy") VALUES($1,$2,$3,$4,$5) ON CONFLICT("documentId","entityType","entityId") DO UPDATE SET label=EXCLUDED.label RETURNING *`,[documentId,input.entityType,Number(input.entityId),input.label||null,userId||null]);await audit(documentId,'LINK',userId,{entityType:input.entityType,entityId:Number(input.entityId)});return r.rows[0]}
export async function removeLink(documentId:number,linkId:number,userId?:number){const r=await query<any>(`DELETE FROM "documentLink" WHERE id=$1 AND "documentId"=$2 RETURNING *`,[linkId,documentId]);if(r.rows[0])await audit(documentId,'UNLINK',userId,{linkId});return r.rows[0]??null}
export async function nextVersion(documentId:number){return Number((await query<any>(`SELECT COALESCE(MAX("versionNo"),0)+1 AS n FROM "documentVersion" WHERE "documentId"=$1`,[documentId])).rows[0].n)}
export async function addVersion(input:{documentId:number;versionNo:number;fileName:string;storageKey:string;mimeType?:string;fileSize:number;sha256:string;changeNote?:string},userId?:number){const c=await pool.connect();try{await c.query('BEGIN');const r=(await c.query<any>(`INSERT INTO "documentVersion"("documentId","versionNo","fileName","storageKey","mimeType","fileSize",sha256,"changeNote","uploadedBy") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[input.documentId,input.versionNo,input.fileName,input.storageKey,input.mimeType||null,input.fileSize,input.sha256,input.changeNote||null,userId||null])).rows[0];await c.query(`UPDATE document SET "currentVersionId"=$2,"updatedAt"=now() WHERE id=$1`,[input.documentId,r.id]);await c.query(`INSERT INTO "documentAudit"("documentId","versionId",action,"userId",metadata) VALUES($1,$2,'UPLOAD',$3,$4)`,[input.documentId,r.id,userId||null,JSON.stringify({fileName:input.fileName,fileSize:input.fileSize})]);await c.query('COMMIT');return r}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
export async function versionById(id:number){return (await query<any>(`SELECT * FROM "documentVersion" WHERE id=$1`,[id])).rows[0]??null}
export async function setStatus(id:number,status:string,userId?:number){const r=(await query<any>(`UPDATE document SET status=$2,"updatedAt"=now() WHERE id=$1 RETURNING *`,[id,status])).rows[0]??null;if(r)await audit(id,status==='ARCHIVED'?'ARCHIVE':'RESTORE',userId,{status});return r}
export async function saveAccess(documentId:number,input:any,userId?:number){await query(`DELETE FROM "documentAccessRule" WHERE "documentId"=$1`,[documentId]);for(const r of input.rules||[]){await query(`INSERT INTO "documentAccessRule"("documentId","roleCode","userId","canView","canEdit","createdBy") VALUES($1,$2,$3,$4,$5,$6)`,[documentId,r.roleCode||null,r.userId||null,r.canView!==false,!!r.canEdit,userId||null])}await audit(documentId,'ACCESS_UPDATE',userId,{count:(input.rules||[]).length});return (await query<any>(`SELECT * FROM "documentAccessRule" WHERE "documentId"=$1 ORDER BY id`,[documentId])).rows}
export async function audit(documentId:number,action:string,userId?:number,metadata?:any,versionId?:number){await query(`INSERT INTO "documentAudit"("documentId","versionId",action,"userId",metadata) VALUES($1,$2,$3,$4,$5)`,[documentId,versionId||null,action,userId||null,metadata?JSON.stringify(metadata):null])}

export async function canAccess(documentId:number,userId:number|undefined,role:string|undefined,edit=false){if(role==='ADMIN')return true;const r=await query<any>(`SELECT EXISTS(SELECT 1 FROM document d WHERE d.id=$1 AND (d."accessLevel"<>'RESTRICTED' OR d."ownerUserId"=$2 OR d."createdBy"=$2 OR EXISTS(SELECT 1 FROM "documentAccessRule" ar WHERE ar."documentId"=d.id AND ${edit?'ar."canEdit"=true':'ar."canView"=true'} AND (ar."userId"=$2 OR ar."roleCode"=$3)))) AS ok`,[documentId,userId||0,role||'']);return !!r.rows[0]?.ok}
export async function summary(){return (await query<any>(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='ACTIVE')::int AS active,COUNT(*) FILTER(WHERE "accessLevel"='RESTRICTED')::int AS restricted,(SELECT COUNT(*)::int FROM "documentVersion") AS versions,COALESCE((SELECT SUM("fileSize") FROM "documentVersion"),0)::bigint AS bytes FROM document`)).rows[0]}
