import { pool, query } from "../db/pool.js";

const invoiceNo=(prefix:string,id:number)=>`${prefix}-${new Date().getFullYear()}-${String(id).padStart(6,"0")}`;
const vatRate=()=>Number(process.env.DEFAULT_VAT_RATE||20);
const grossParts=(gross:number,rate=vatRate())=>{const subtotal=rate>0?gross/(1+rate/100):gross;return {subtotal:Number(subtotal.toFixed(2)),vatTotal:Number((gross-subtotal).toFixed(2)),grandTotal:Number(gross.toFixed(2)),rate}};

async function insertInvoice(c:any,input:{prefix:string;direction:'SALE'|'PURCHASE';customerId?:number|null;supplierId?:number|null;sourceType:string;sourceId:number;issueDate:string;dueDate?:string|null;currency?:string;subtotal:number;vatTotal:number;grandTotal:number;notes:string;item:{productId?:number|null;description:string;quantity:number;unitPrice:number;vatRate:number;lineTotal:number}}){
  const exists=(await c.query(`SELECT id FROM "commercialInvoice" WHERE direction=$1 AND "sourceType"=$2 AND "sourceId"=$3`,[input.direction,input.sourceType,input.sourceId])).rows[0];
  if(exists)return exists.id;
  const id=(await c.query(`INSERT INTO "commercialInvoice"("invoiceNo",direction,"customerId","supplierId","sourceType","sourceId","issueDate","dueDate",currency,subtotal,"vatTotal","grandTotal",status,notes,"accountingReady","eDocumentStatus") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'READY',$13,true,'READY') RETURNING id`,[
    `TMP-${input.prefix}-${input.sourceId}`,input.direction,input.customerId||null,input.supplierId||null,input.sourceType,input.sourceId,input.issueDate,input.dueDate||null,input.currency||'TRY',input.subtotal,input.vatTotal,input.grandTotal,input.notes
  ])).rows[0].id;
  await c.query(`UPDATE "commercialInvoice" SET "invoiceNo"=$2 WHERE id=$1`,[id,invoiceNo(input.prefix,id)]);
  await c.query(`INSERT INTO "commercialInvoiceItem"("invoiceId","productId",description,quantity,"unitPrice","vatRate","lineTotal") VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,input.item.productId||null,input.item.description,input.item.quantity,input.item.unitPrice,input.item.vatRate,input.item.lineTotal]);
  return id;
}

export async function syncSourceInvoices(){
  const c=await pool.connect();
  try{
    await c.query("BEGIN");
    const sales=(await c.query<any>(`SELECT o.* FROM "salesOrder" o WHERE o.status<>'CANCELLED' AND o."grandTotal">0`)).rows;
    for(const o of sales){
      const existing=(await c.query<any>(`SELECT id FROM "commercialInvoice" WHERE direction='SALE' AND "sourceType"='SALES_ORDER' AND "sourceId"=$1`,[o.id])).rows[0];
      if(!existing){
        const id=(await c.query<any>(`INSERT INTO "commercialInvoice"("invoiceNo",direction,"customerId","sourceType","sourceId","issueDate","dueDate",currency,subtotal,"vatTotal","grandTotal",status,notes,"accountingReady","eDocumentStatus") VALUES($1,'SALE',$2,'SALES_ORDER',$3,$4,$5,$6,$7,$8,$9,'READY',$10,true,'READY') RETURNING id`,[`TMP-S-${o.id}`,o.customerId,o.id,new Date(o.createdAt).toISOString().slice(0,10),new Date(Date.parse(o.createdAt)+30*86400000).toISOString().slice(0,10),o.currency,o.subtotal,o.vatTotal,o.grandTotal,`Satış siparişi ${o.orderNo}`])).rows[0].id;
        await c.query(`UPDATE "commercialInvoice" SET "invoiceNo"=$2 WHERE id=$1`,[id,invoiceNo("SF",id)]);
        await c.query(`INSERT INTO "commercialInvoiceItem"("invoiceId","productId",description,quantity,"unitPrice","vatRate","lineTotal") SELECT $1,"productId",description,quantity,"unitPrice","vatRate","lineTotal" FROM "salesOrderItem" WHERE "salesOrderId"=$2`,[id,o.id]);
      }
    }
    const purchase=(await c.query<any>(`SELECT o.* FROM "purchaseOrder" o WHERE o.status<>'CANCELLED' AND o."grandTotal">0`)).rows;
    for(const o of purchase){
      const existing=(await c.query<any>(`SELECT id FROM "commercialInvoice" WHERE direction='PURCHASE' AND "sourceType"='PURCHASE_ORDER' AND "sourceId"=$1`,[o.id])).rows[0];
      if(!existing){
        const id=(await c.query<any>(`INSERT INTO "commercialInvoice"("invoiceNo",direction,"supplierId","sourceType","sourceId","issueDate","dueDate",currency,subtotal,"vatTotal","grandTotal",status,notes,"accountingReady","eDocumentStatus") VALUES($1,'PURCHASE',$2,'PURCHASE_ORDER',$3,$4,$5,$6,$7,$8,$9,'READY',$10,true,'READY') RETURNING id`,[`TMP-P-${o.id}`,o.supplierId,o.id,new Date(o.createdAt).toISOString().slice(0,10),o.expectedAt||new Date(Date.parse(o.createdAt)+30*86400000).toISOString().slice(0,10),o.currency,o.subtotal,o.vatTotal,o.grandTotal,`Satın alma siparişi ${o.orderNo}`])).rows[0].id;
        await c.query(`UPDATE "commercialInvoice" SET "invoiceNo"=$2 WHERE id=$1`,[id,invoiceNo("AF",id)]);
        await c.query(`INSERT INTO "commercialInvoiceItem"("invoiceId","productId",description,quantity,"unitPrice","vatRate","lineTotal") SELECT $1,"productId",description,quantity,"unitPrice","vatRate","lineTotal" FROM "purchaseOrderItem" WHERE "orderId"=$2`,[id,o.id]);
      }
    }
    const services=(await c.query<any>(`SELECT sr.*,c.name AS "customerName" FROM "serviceRecord" sr JOIN customer c ON c.id=sr."customerId" WHERE sr."serviceType"='PAID' AND sr."grandTotal">0 AND sr.status NOT IN ('CANCELLED')`)).rows;
    for(const sr of services){const g=grossParts(Number(sr.grandTotal));await insertInvoice(c,{prefix:'SV',direction:'SALE',customerId:sr.customerId,sourceType:'SERVICE',sourceId:sr.id,issueDate:new Date(sr.completedAt||sr.receivedAt||Date.now()).toISOString().slice(0,10),dueDate:new Date(Date.parse(sr.completedAt||sr.receivedAt||new Date().toISOString())+15*86400000).toISOString().slice(0,10),subtotal:g.subtotal,vatTotal:g.vatTotal,grandTotal:g.grandTotal,notes:`Teknik servis ${sr.serviceNo}`,item:{description:`Teknik servis hizmeti ${sr.serviceNo}`,quantity:1,unitPrice:g.subtotal,vatRate:g.rate,lineTotal:g.subtotal}})}
    const subs=(await c.query<any>(`SELECT cs.*,cp.name AS "packageName" FROM "corsSubscription" cs JOIN "corsPackage" cp ON cp.id=cs."packageId" WHERE cs.amount>0 AND cs.status<>'CANCELLED'`)).rows;
    for(const cs of subs){const g=grossParts(Number(cs.amount));await insertInvoice(c,{prefix:'CRS',direction:'SALE',customerId:cs.customerId,sourceType:'CORS_SUBSCRIPTION',sourceId:cs.id,issueDate:String(cs.startDate).slice(0,10),dueDate:String(cs.startDate).slice(0,10),currency:cs.currency,subtotal:g.subtotal,vatTotal:g.vatTotal,grandTotal:g.grandTotal,notes:`CORS aboneliği ${cs.subscriptionNo}`,item:{description:`${cs.packageName} · ${cs.username}`,quantity:1,unitPrice:g.subtotal,vatRate:g.rate,lineTotal:g.subtotal}})}
    const renewals=(await c.query<any>(`SELECT r.*,cs."customerId",cs."subscriptionNo",cs.username,cs.currency,cp.name AS "packageName" FROM "corsSubscriptionRenewal" r JOIN "corsSubscription" cs ON cs.id=r."subscriptionId" JOIN "corsPackage" cp ON cp.id=cs."packageId" WHERE r.amount>0`)).rows;
    for(const r of renewals){const g=grossParts(Number(r.amount));await insertInvoice(c,{prefix:'CRY',direction:'SALE',customerId:r.customerId,sourceType:'CORS_RENEWAL',sourceId:r.id,issueDate:new Date(r.createdAt).toISOString().slice(0,10),dueDate:new Date(r.createdAt).toISOString().slice(0,10),currency:r.currency,subtotal:g.subtotal,vatTotal:g.vatTotal,grandTotal:g.grandTotal,notes:`CORS yenileme ${r.subscriptionNo}`,item:{description:`${r.packageName} yenileme · ${r.username}`,quantity:1,unitPrice:g.subtotal,vatRate:g.rate,lineTotal:g.subtotal}})}
    const rentals=(await c.query<any>(`SELECT r.*,c.name AS "customerName",COALESCE(x.damage,0) AS damage FROM "rentalAgreement" r JOIN customer c ON c.id=r."customerId" LEFT JOIN (SELECT "rentalId",SUM("damageCharge") damage FROM "rentalItem" GROUP BY "rentalId") x ON x."rentalId"=r.id WHERE r.status='RETURNED'`)).rows;
    for(const r of rentals){
      const days=Math.max(1,Math.ceil((new Date(r.actualReturnDate).getTime()-new Date(r.startDate).getTime())/86400000)+1);const months=Math.max(1,Math.ceil(days/30));
      let total=r.type==='DEMO'||r.billingPeriod==='FREE'?0:r.billingPeriod==='DAILY'?days*Number(r.dailyRate||0):r.billingPeriod==='MONTHLY'?months*Number(r.monthlyRate||0):Number(r.fixedAmount||0);total+=Number(r.damage||0);
      if(total>0){const g=grossParts(total);await insertInvoice(c,{prefix:'KIR',direction:'SALE',customerId:r.customerId,sourceType:'RENTAL',sourceId:r.id,issueDate:String(r.actualReturnDate).slice(0,10),dueDate:String(r.actualReturnDate).slice(0,10),currency:r.currency,subtotal:g.subtotal,vatTotal:g.vatTotal,grandTotal:g.grandTotal,notes:`Kiralama ${r.rentalNo}`,item:{description:`Cihaz kiralama ${r.rentalNo}`,quantity:1,unitPrice:g.subtotal,vatRate:g.rate,lineTotal:g.subtotal}})}
    }
    await c.query("COMMIT");
  }catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}
}

export async function listInvoices(direction?:string,status?:string){await syncSourceInvoices();const vals:any[]=[];const where:string[]=[];if(direction){vals.push(direction);where.push(`i.direction=$${vals.length}`)}if(status){vals.push(status);where.push(`i.status=$${vals.length}`)}return (await query<any>(`SELECT i.*,c.name AS "customerName",s.name AS "supplierName",COUNT(ii.id)::int AS "itemCount" FROM "commercialInvoice" i LEFT JOIN customer c ON c.id=i."customerId" LEFT JOIN supplier s ON s.id=i."supplierId" LEFT JOIN "commercialInvoiceItem" ii ON ii."invoiceId"=i.id ${where.length?`WHERE ${where.join(" AND ")}`:""} GROUP BY i.id,c.name,s.name ORDER BY i.id DESC`,vals)).rows}
export async function getInvoice(id:number){const invoice=(await query<any>(`SELECT i.*,c.name AS "customerName",c."taxNumber" AS "customerTaxNumber",c."taxOffice" AS "customerTaxOffice",c.email AS "customerEmail",c.address AS "customerAddress",c.city AS "customerCity",s.name AS "supplierName",s."taxNumber" AS "supplierTaxNumber",s."taxOffice" AS "supplierTaxOffice",s.email AS "supplierEmail",s.address AS "supplierAddress",s.city AS "supplierCity" FROM "commercialInvoice" i LEFT JOIN customer c ON c.id=i."customerId" LEFT JOIN supplier s ON s.id=i."supplierId" WHERE i.id=$1`,[id])).rows[0];if(!invoice)return null;invoice.items=(await query<any>(`SELECT ii.*,p.sku,p.name AS "productName",p.unit FROM "commercialInvoiceItem" ii LEFT JOIN product p ON p.id=ii."productId" WHERE ii."invoiceId"=$1 ORDER BY ii.id`,[id])).rows;return invoice}
export async function markSync(id:number,input:{status:string;externalId?:string|null;externalNo?:string|null;error?:string|null}){return (await query<any>(`UPDATE "commercialInvoice" SET status=$2,"externalProvider"='PARASUT',"externalId"=COALESCE($3,"externalId"),"externalNo"=COALESCE($4,"externalNo"),"syncError"=$5,"lastSyncAt"=now(),"eDocumentStatus"=CASE WHEN $2='SYNCED' THEN 'SENT' WHEN $2='ERROR' THEN 'ERROR' ELSE "eDocumentStatus" END,"updatedAt"=now() WHERE id=$1 RETURNING *`,[id,input.status,input.externalId||null,input.externalNo||null,input.error||null])).rows[0]}
export async function getLink(entityType:string,localId:number){return (await query<any>(`SELECT * FROM "integrationLink" WHERE provider='PARASUT' AND "entityType"=$1 AND "localId"=$2`,[entityType,localId])).rows[0]||null}
export async function saveLink(entityType:string,localId:number,externalId:string,externalCode?:string){return (await query<any>(`INSERT INTO "integrationLink"(provider,"entityType","localId","externalId","externalCode") VALUES('PARASUT',$1,$2,$3,$4) ON CONFLICT(provider,"entityType","localId") DO UPDATE SET "externalId"=EXCLUDED."externalId","externalCode"=EXCLUDED."externalCode","lastSyncAt"=now() RETURNING *`,[entityType,localId,externalId,externalCode||null])).rows[0]}
export async function logSync(action:string,entityType:string|null,localId:number|null,status:string,message:string,externalId?:string|null){await query(`INSERT INTO "integrationSyncLog"(provider,action,"entityType","localId","externalId",status,message) VALUES('PARASUT',$1,$2,$3,$4,$5,$6)`,[action,entityType,localId,externalId||null,status,message])}
export async function syncLogs(){return (await query<any>(`SELECT * FROM "integrationSyncLog" WHERE provider='PARASUT' ORDER BY id DESC LIMIT 100`)).rows}
export async function getFinanceTransactionForParasut(id:number){return (await query<any>(`SELECT t.*,fd."sourceType",fd."sourceId",ci.id AS "invoiceId",ci.direction,ci."externalId" AS "invoiceExternalId",ci.status AS "invoiceStatus" FROM "financeTransaction" t JOIN "financeAllocation" fa ON fa."transactionId"=t.id JOIN "financeDocument" fd ON fd.id=fa."documentId" LEFT JOIN "commercialInvoice" ci ON ci."sourceType"=fd."sourceType" AND ci."sourceId"=fd."sourceId" WHERE t.id=$1 LIMIT 1`,[id])).rows[0]||null}
export async function vatReport(from?:string,to?:string){const vals:any[]=[];const wh=[`status<>'CANCELLED'`];if(from){vals.push(from);wh.push(`"issueDate">=$${vals.length}`)}if(to){vals.push(to);wh.push(`"issueDate"<=$${vals.length}`)}return (await query<any>(`SELECT direction,COALESCE(SUM(subtotal),0)::text AS subtotal,COALESCE(SUM("vatTotal"),0)::text AS "vatTotal",COALESCE(SUM("grandTotal"),0)::text AS "grandTotal",COUNT(*)::int AS count FROM "commercialInvoice" WHERE ${wh.join(' AND ')} GROUP BY direction ORDER BY direction`,vals)).rows}
export async function accountMappings(){return (await query<any>(`SELECT a.id,a.code,a.name,a.type,a.currency,m."externalAccountId",m."externalAccountName",COALESCE(m."isActive",false) AS "mapped" FROM "financeAccount" a LEFT JOIN "parasutAccountMapping" m ON m."financeAccountId"=a.id ORDER BY a.id`)).rows}
export async function saveAccountMapping(financeAccountId:number,externalAccountId:string,externalAccountName?:string|null){return (await query<any>(`INSERT INTO "parasutAccountMapping"("financeAccountId","externalAccountId","externalAccountName") VALUES($1,$2,$3) ON CONFLICT("financeAccountId") DO UPDATE SET "externalAccountId"=EXCLUDED."externalAccountId","externalAccountName"=EXCLUDED."externalAccountName","isActive"=true,"updatedAt"=now() RETURNING *`,[financeAccountId,externalAccountId,externalAccountName||null])).rows[0]}
export async function getAccountMapping(financeAccountId:number){return (await query<any>(`SELECT * FROM "parasutAccountMapping" WHERE "financeAccountId"=$1 AND "isActive"=true`,[financeAccountId])).rows[0]||null}
export async function eDocumentReadiness(){await syncSourceInvoices();return (await query<any>(`SELECT i.id,i."invoiceNo",i.direction,i."sourceType",i.status,i."eDocumentType",i."eDocumentStatus",COALESCE(c.name,s.name) AS "partyName",COALESCE(c."taxNumber",s."taxNumber") AS "taxNumber",COALESCE(c.address,s.address) AS address,COALESCE(c.city,s.city) AS city,(COALESCE(c."taxNumber",s."taxNumber") IS NOT NULL AND COALESCE(c.address,s.address) IS NOT NULL AND COALESCE(c.city,s.city) IS NOT NULL) AS ready FROM "commercialInvoice" i LEFT JOIN customer c ON c.id=i."customerId" LEFT JOIN supplier s ON s.id=i."supplierId" WHERE i.status<>'CANCELLED' ORDER BY i.id DESC`)).rows}
export async function enqueueSyncJob(action:string,entityType:string,localId:number,createdBy?:number|null){return (await query<any>(`INSERT INTO "integrationSyncJob"(provider,action,"entityType","localId","createdBy") VALUES('PARASUT',$1,$2,$3,$4) ON CONFLICT(provider,action,"entityType","localId") DO UPDATE SET status=CASE WHEN "integrationSyncJob".status='SUCCESS' THEN 'SUCCESS' ELSE 'PENDING' END,"nextAttemptAt"=now(),"lastError"=NULL,"updatedAt"=now() RETURNING *`,[action,entityType,localId,createdBy||null])).rows[0]}
export async function syncJobs(status?:string){const vals:any[]=[];let where=`provider='PARASUT'`;if(status){vals.push(status);where+=` AND status=$${vals.length}`}return (await query<any>(`SELECT * FROM "integrationSyncJob" WHERE ${where} ORDER BY CASE status WHEN 'FAILED' THEN 0 WHEN 'RETRY' THEN 1 WHEN 'PENDING' THEN 2 ELSE 3 END,"createdAt" DESC LIMIT 250`,vals)).rows}
export async function claimSyncJobs(limit=10){return (await query<any>(`WITH picked AS (SELECT id FROM "integrationSyncJob" WHERE provider='PARASUT' AND status IN('PENDING','RETRY') AND "nextAttemptAt"<=now() AND attempts<"maxAttempts" ORDER BY "nextAttemptAt",id FOR UPDATE SKIP LOCKED LIMIT $1) UPDATE "integrationSyncJob" j SET status='PROCESSING',"lockedAt"=now(),"updatedAt"=now() FROM picked WHERE j.id=picked.id RETURNING j.*`,[Math.max(1,Math.min(limit,50))])).rows}
export async function finishSyncJob(id:number,externalId?:string|null){return (await query<any>(`UPDATE "integrationSyncJob" SET status='SUCCESS',attempts=attempts+1,"externalId"=$2,"lastError"=NULL,"lockedAt"=NULL,"updatedAt"=now() WHERE id=$1 RETURNING *`,[id,externalId||null])).rows[0]}
export async function failSyncJob(id:number,error:string){return (await query<any>(`UPDATE "integrationSyncJob" SET attempts=attempts+1,status=CASE WHEN attempts+1>="maxAttempts" THEN 'FAILED' ELSE 'RETRY' END,"nextAttemptAt"=now()+make_interval(mins=>LEAST(60,POWER(2,attempts)::int)),"lastError"=$2,"lockedAt"=NULL,"updatedAt"=now() WHERE id=$1 RETURNING *`,[id,error.slice(0,2000)])).rows[0]}
export async function retrySyncJob(id:number){return (await query<any>(`UPDATE "integrationSyncJob" SET status='PENDING',attempts=0,"nextAttemptAt"=now(),"lastError"=NULL,"lockedAt"=NULL,"updatedAt"=now() WHERE id=$1 AND provider='PARASUT' RETURNING *`,[id])).rows[0]||null}
export async function syncQueueSummary(){return (await query<any>(`SELECT count(*) FILTER(WHERE status='PENDING')::int pending,count(*) FILTER(WHERE status='RETRY')::int retry,count(*) FILTER(WHERE status='FAILED')::int failed,count(*) FILTER(WHERE status='SUCCESS')::int success FROM "integrationSyncJob" WHERE provider='PARASUT'`)).rows[0]}
