import {query} from "../db/pool.js";
export async function companies(){return (await query(`SELECT * FROM "groupCompany" WHERE "isActive"=TRUE ORDER BY name`)).rows}
export async function departments(){return (await query(`SELECT d.*,g.name "companyName",e."firstName"||' '||e."lastName" "managerName" FROM department d LEFT JOIN "groupCompany" g ON g.id=d."companyId" LEFT JOIN employee e ON e.id=d."managerEmployeeId" ORDER BY d.name`)).rows}
export async function employees(q?:string){const v=q?['%'+q+'%']:[];return (await query(`SELECT e.*,g.name "companyName",d.name "departmentName",m."firstName"||' '||m."lastName" "managerName" FROM employee e JOIN "groupCompany" g ON g.id=e."companyId" LEFT JOIN department d ON d.id=e."departmentId" LEFT JOIN employee m ON m.id=e."managerId" ${q?`WHERE e."firstName" ILIKE $1 OR e."lastName" ILIKE $1 OR e."employeeNo" ILIKE $1 OR COALESCE(e.title,'') ILIKE $1`:''} ORDER BY e."firstName",e."lastName"`,v)).rows}
export async function employee(id:number){const e=(await query(`SELECT e.*,g.name "companyName",d.name "departmentName",m."firstName"||' '||m."lastName" "managerName" FROM employee e JOIN "groupCompany" g ON g.id=e."companyId" LEFT JOIN department d ON d.id=e."departmentId" LEFT JOIN employee m ON m.id=e."managerId" WHERE e.id=$1`,[id])).rows[0];if(!e)return null;const assignments=(await query(`SELECT a.*,hc.name "homeCompanyName",ac.name "assignedCompanyName",p.name "projectName" FROM "employeeAssignment" a JOIN "groupCompany" hc ON hc.id=a."homeCompanyId" JOIN "groupCompany" ac ON ac.id=a."assignedCompanyId" LEFT JOIN project p ON p.id=a."projectId" WHERE a."employeeId"=$1 ORDER BY a."startDate" DESC`,[id])).rows;return {...e,assignments}}
export async function createEmployee(x:any){const r=await query(`INSERT INTO employee("employeeNo","userId","companyId","departmentId","managerId","firstName","lastName",title,email,phone,"employmentType",status,"hireDate",skills,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[x.employeeNo,x.userId||null,x.companyId,x.departmentId||null,x.managerId||null,x.firstName,x.lastName,x.title||null,x.email||null,x.phone||null,x.employmentType||'FULL_TIME',x.status||'ACTIVE',x.hireDate||null,x.skills||[],x.notes||null]);return r.rows[0]}
export async function addAssignment(employeeId:number,x:any,userId?:number){const availability=await employeeAvailability(employeeId,x.startDate,x.endDate||x.startDate);if(!availability.available)throw new Error("Personel seçilen tarihlerde izinli veya başka bir görevlendirmede.");const emp=(await query(`SELECT "companyId" FROM employee WHERE id=$1`,[employeeId])).rows[0];if(!emp)throw new Error("Personel bulunamadı.");const r=await query(`INSERT INTO "employeeAssignment"("employeeId","homeCompanyId","assignedCompanyId","projectId",type,title,description,"startDate","endDate",status,"createdBy") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[employeeId,emp.companyId,x.assignedCompanyId,x.projectId||null,x.type||'PROJECT',x.title,x.description||null,x.startDate,x.endDate||null,x.status||'ACTIVE',userId||null]);return r.rows[0]}
export async function summary(){return (await query(`SELECT COUNT(*) FILTER(WHERE status='ACTIVE')::int active,COUNT(*) FILTER(WHERE status='ON_LEAVE')::int leave,(SELECT COUNT(*)::int FROM "employeeAssignment" WHERE status='ACTIVE') assignments,(SELECT COUNT(*)::int FROM "employeeAssignment" WHERE status='ACTIVE' AND "homeCompanyId"<>"assignedCompanyId") cross_company FROM employee`)).rows[0]}

export async function employeeAvailability(employeeId:number,startDate:string,endDate:string){
 const leave=(await query(`SELECT * FROM "employeeLeave" WHERE "employeeId"=$1 AND status='APPROVED' AND "startDate"<=$3 AND "endDate">=$2`,[employeeId,startDate,endDate])).rows;
 const assignments=(await query(`SELECT a.*,g.name "assignedCompanyName",p.name "projectName" FROM "employeeAssignment" a JOIN "groupCompany" g ON g.id=a."assignedCompanyId" LEFT JOIN project p ON p.id=a."projectId" WHERE a."employeeId"=$1 AND a.status IN ('PLANNED','ACTIVE') AND a."startDate"<=$3 AND COALESCE(a."endDate",'9999-12-31')>=$2`,[employeeId,startDate,endDate])).rows;
 return {available:leave.length===0&&assignments.length===0,leave,assignments};
}
export async function leaves(employeeId?:number){return (await query(`SELECT l.*,e."firstName"||' '||e."lastName" "employeeName" FROM "employeeLeave" l JOIN employee e ON e.id=l."employeeId" ${employeeId?`WHERE l."employeeId"=$1`:''} ORDER BY l."startDate" DESC`,employeeId?[employeeId]:[])).rows}
export async function createLeave(employeeId:number,x:any,userId?:number){return (await query(`INSERT INTO "employeeLeave"("employeeId",type,status,"startDate","endDate",reason,"createdBy") VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[employeeId,x.type||'ANNUAL',x.status||'PENDING',x.startDate,x.endDate,x.reason||null,userId||null])).rows[0]}
export async function setLeaveStatus(id:number,status:string,userId?:number){return (await query(`UPDATE "employeeLeave" SET status=$2,"approvedBy"=CASE WHEN $2 IN ('APPROVED','REJECTED') THEN $3 ELSE "approvedBy" END,"updatedAt"=NOW() WHERE id=$1 RETURNING *`,[id,status,userId||null])).rows[0]}
export async function certifications(employeeId:number){return (await query(`SELECT * FROM "employeeCertification" WHERE "employeeId"=$1 ORDER BY "validUntil" NULLS LAST,name`,[employeeId])).rows}
export async function createCertification(employeeId:number,x:any,userId?:number){return (await query(`INSERT INTO "employeeCertification"("employeeId",name,issuer,"certificateNo","issuedAt","validUntil","documentId",notes,"createdBy") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[employeeId,x.name,x.issuer||null,x.certificateNo||null,x.issuedAt||null,x.validUntil||null,x.documentId||null,x.notes||null,userId||null])).rows[0]}
export async function trainings(employeeId:number){return (await query(`SELECT * FROM "employeeTraining" WHERE "employeeId"=$1 ORDER BY "startDate" DESC NULLS LAST`,[employeeId])).rows}
export async function createTraining(employeeId:number,x:any,userId?:number){return (await query(`INSERT INTO "employeeTraining"("employeeId",title,provider,status,"startDate","endDate",notes,"createdBy") VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[employeeId,x.title,x.provider||null,x.status||'PLANNED',x.startDate||null,x.endDate||null,x.notes||null,userId||null])).rows[0]}
export async function hrSummary(){return (await query(`SELECT (SELECT COUNT(*) FROM "employeeLeave" WHERE status='APPROVED' AND CURRENT_DATE BETWEEN "startDate" AND "endDate")::int "onLeaveToday",(SELECT COUNT(*) FROM "employeeLeave" WHERE status='PENDING')::int "pendingLeaves",(SELECT COUNT(*) FROM "employeeCertification" WHERE "validUntil" BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::int "certExpiring",(SELECT COUNT(*) FROM "employeeTraining" WHERE status IN ('PLANNED','IN_PROGRESS'))::int "activeTrainings"`)).rows[0]}
