import{query}from"../db/pool.js";
export async function executiveAnalytics(months=12){
 const [sales,finance,service,cors,projects,stock,expenses]=await Promise.all([
 query(`SELECT COALESCE(SUM("grandTotal") FILTER(WHERE status<>'CANCELLED'),0) revenue,COUNT(*) FILTER(WHERE status<>'CANCELLED')::int orders,COALESCE(AVG("grandTotal") FILTER(WHERE status<>'CANCELLED'),0) "avgOrder" FROM "salesOrder" WHERE "createdAt">=date_trunc('month',NOW())`),
 query(`SELECT COALESCE(SUM(amount-"paidAmount") FILTER(WHERE direction='RECEIVABLE' AND status IN('OPEN','PARTIAL')),0) receivables,COALESCE(SUM(amount-"paidAmount") FILTER(WHERE direction='RECEIVABLE' AND status IN('OPEN','PARTIAL') AND "dueDate"<CURRENT_DATE),0) overdue,COALESCE(SUM(amount-"paidAmount") FILTER(WHERE direction='PAYABLE' AND status IN('OPEN','PARTIAL')),0) payables FROM "financeDocument"`),
 query(`SELECT COUNT(*) FILTER(WHERE status NOT IN('DELIVERED','CANCELLED'))::int open,COUNT(*) FILTER(WHERE "createdAt">=date_trunc('month',NOW()))::int "monthCount",COALESCE(SUM("grandTotal") FILTER(WHERE "createdAt">=date_trunc('month',NOW())),0) "monthValue" FROM "serviceRecord"`),
 query(`SELECT COUNT(*) FILTER(WHERE status='ACTIVE')::int active,COUNT(*) FILTER(WHERE status='ACTIVE' AND "endDate"<=CURRENT_DATE+30)::int expiring,COALESCE(SUM(amount) FILTER(WHERE status='ACTIVE'),0) "activeValue" FROM "corsSubscription"`),
 query(`SELECT COUNT(*) FILTER(WHERE status='ACTIVE')::int active,COALESCE(AVG(progress) FILTER(WHERE status='ACTIVE'),0) progress,COUNT(*) FILTER(WHERE status='ACTIVE' AND "targetEndDate"<CURRENT_DATE)::int delayed FROM project`),
 query(`SELECT COUNT(*) FILTER(WHERE "stockQuantity"<=criticalStock)::int critical,COALESCE(SUM("stockQuantity"),0) units FROM product WHERE status='ACTIVE'`),
 query(`SELECT COALESCE(SUM(amount) FILTER(WHERE status IN('APPROVED','PAID') AND "expenseDate">=date_trunc('month',CURRENT_DATE)),0) "monthFieldCost" FROM "fieldExpense"`)
 ]);
 const trend=(await query(`SELECT to_char(m,'YYYY-MM') month,COALESCE(s.total,0) sales,COALESCE(f.receipts,0) receipts FROM generate_series(date_trunc('month',NOW())-(($1::int-1)*INTERVAL '1 month'),date_trunc('month',NOW()),INTERVAL '1 month') m LEFT JOIN (SELECT date_trunc('month',"createdAt") m,SUM("grandTotal") total FROM "salesOrder" WHERE status<>'CANCELLED' GROUP BY 1)s ON s.m=m LEFT JOIN (SELECT date_trunc('month',"transactionDate") m,SUM(amount) receipts FROM "financeTransaction" WHERE type='RECEIPT' GROUP BY 1)f ON f.m=m ORDER BY m`,[Math.max(3,Math.min(months,24))])).rows;
 return{sales:sales.rows[0],finance:finance.rows[0],service:service.rows[0],cors:cors.rows[0],projects:projects.rows[0],stock:stock.rows[0],expenses:expenses.rows[0],trend};
}
export async function salesByCustomer(limit=10){return(await query(`SELECT c.id,c.name,COUNT(o.id)::int orders,COALESCE(SUM(o."grandTotal"),0) revenue FROM customer c JOIN "salesOrder" o ON o."customerId"=c.id AND o.status<>'CANCELLED' GROUP BY c.id,c.name ORDER BY revenue DESC LIMIT $1`,[limit])).rows}
export async function projectProfitability(){return(await query(`SELECT p.id,p.code,p.name,p.status,p.progress,COALESCE(e.cost,0) "fieldCost" FROM project p LEFT JOIN(SELECT "projectId",SUM(amount) cost FROM "fieldExpense" WHERE status IN('APPROVED','PAID') GROUP BY "projectId")e ON e."projectId"=p.id ORDER BY p."createdAt" DESC`)).rows}
