import { query } from "../db/pool.js";

export async function listWorkTasks(filters:{userId?:number;status?:string;scope?:string;q?:string}={}){
 const w:string[]=[]; const v:unknown[]=[];
 if(filters.scope==='mine'&&filters.userId){v.push(filters.userId);w.push(`"assignedUserId"=$${v.length}`)}
 if(filters.status){v.push(filters.status);w.push(`status=$${v.length}`)}
 if(filters.q){v.push(`%${filters.q}%`);w.push(`(title ILIKE $${v.length} OR COALESCE("taskNo",'') ILIKE $${v.length} OR COALESCE("sourceLabel",'') ILIKE $${v.length})`)}
 return (await query(`SELECT *, CASE WHEN "dueAt" IS NOT NULL AND "dueAt"<now() AND status NOT IN ('DONE','CANCELLED') THEN true ELSE false END AS overdue FROM "workTask" ${w.length?'WHERE '+w.join(' AND '):''} ORDER BY CASE WHEN status='IN_PROGRESS' THEN 1 WHEN priority='URGENT' THEN 2 WHEN priority='HIGH' THEN 3 ELSE 4 END,"dueAt" NULLS LAST,"createdAt" DESC`,v)).rows
}
export async function getWorkTask(id:number){return (await query(`SELECT *, CASE WHEN "dueAt" IS NOT NULL AND "dueAt"<now() AND status NOT IN ('DONE','CANCELLED') THEN true ELSE false END AS overdue FROM "workTask" WHERE id=$1`,[id])).rows[0]??null}
export async function workTaskSummary(userId:number){return (await query(`SELECT count(*) FILTER(WHERE "assignedUserId"=$1 AND status NOT IN ('DONE','CANCELLED'))::int AS mine, count(*) FILTER(WHERE "assignedUserId"=$1 AND status='IN_PROGRESS')::int AS "inProgress", count(*) FILTER(WHERE "assignedUserId"=$1 AND "dueAt"<now() AND status NOT IN ('DONE','CANCELLED'))::int AS overdue, count(*) FILTER(WHERE "assignedUserId"=$1 AND "dueAt" BETWEEN now() AND now()+interval '7 days' AND status NOT IN ('DONE','CANCELLED'))::int AS "due7", count(*) FILTER(WHERE status NOT IN ('DONE','CANCELLED'))::int AS team FROM "workTask"`,[userId])).rows[0]}
export async function createWorkTask(input:any,user:any){const no=`WRK-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;return (await query(`INSERT INTO "workTask" ("taskNo",title,description,"sourceType","sourceId","sourceLabel",status,priority,"assignedUserId","assignedUserName",department,"companyId","companyName","createdBy","createdByName","startAt","dueAt",progress,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) RETURNING *`,[no,input.title,input.description??null,input.sourceType??'GENERAL',input.sourceId??null,input.sourceLabel??null,input.status??'TODO',input.priority??'NORMAL',input.assignedUserId??user.id,input.assignedUserName??user.name,input.department??user.department??null,input.companyId??null,input.companyName??null,user.id,user.name,input.startAt??null,input.dueAt??null,Number(input.progress??0),input.notes??null])).rows[0]}
export async function updateWorkTask(id:number,input:any){const cur=await getWorkTask(id);if(!cur)throw new Error('Görev bulunamadı.');const status=input.status??cur.status;let progress=input.progress!==undefined?Number(input.progress):cur.progress;if(status==='DONE')progress=100;return (await query(`UPDATE "workTask" SET title=COALESCE($2,title),description=COALESCE($3,description),status=$4,priority=COALESCE($5,priority),"assignedUserId"=COALESCE($6,"assignedUserId"),"assignedUserName"=COALESCE($7,"assignedUserName"),department=COALESCE($8,department),"companyId"=COALESCE($9,"companyId"),"companyName"=COALESCE($10,"companyName"),"dueAt"=COALESCE($11,"dueAt"),progress=$12,notes=COALESCE($13,notes),"completedAt"=CASE WHEN $4='DONE' THEN COALESCE("completedAt",now()) ELSE NULL END,"updatedAt"=now() WHERE id=$1 RETURNING *`,[id,input.title??null,input.description??null,status,input.priority??null,input.assignedUserId??null,input.assignedUserName??null,input.department??null,input.companyId??null,input.companyName??null,input.dueAt??null,progress,input.notes??null])).rows[0]}
export async function syncOverdueNotifications(){await query(`INSERT INTO "notification" (type,severity,title,message,"entityType","entityId","actionUrl","dedupeKey") SELECT 'TASK_OVERDUE','CRITICAL','Geciken görev: '||title, COALESCE("assignedUserName",'Atanmamış')||' · '||to_char("dueAt",'DD.MM.YYYY HH24:MI'),'WORK_TASK',id,'/tasks/'||id,'task-overdue-'||id FROM "workTask" WHERE "dueAt"<now() AND status NOT IN ('DONE','CANCELLED') ON CONFLICT ("dedupeKey") DO NOTHING`)}
